//! Native Story → Lua compiler. Calls and argument ordering preserve the v3 Host contract.
use anyhow::{bail, Result};
use serde_json::{json, Value};
use std::{path::Path, sync::OnceLock};

pub const GENERATED_MARK: &str = "-- Generated by lomc, do not edit";
pub fn lua_str(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
    )
}
pub fn lua_num(v: &Value) -> Result<String> {
    let Some(number) = v.as_number() else {
        bail!("内部错误：布尔值或非数值不能作为数值 emit")
    };
    let lexical = number.to_string();
    if !lexical.contains(['.', 'e', 'E']) {
        return Ok(lexical);
    }
    let f = number
        .as_f64()
        .ok_or_else(|| anyhow::anyhow!("内部错误：数值必须是有限值"))?;
    if !f.is_finite() {
        bail!("内部错误：数值必须是有限值")
    }
    if f.fract() == 0.0 && f.abs() < 1e15 {
        return Ok(if f == 0.0 {
            "0".into()
        } else {
            format!("{f:.0}")
        });
    }
    // Rust's shortest representation has the same mantissa as Python repr, but
    // Python starts scientific notation at 1e16 / below 1e-4 and pads exponents.
    let raw = if f != 0.0 && (f.abs() < 1e-4 || f.abs() >= 1e16) {
        format!("{f:e}")
    } else {
        format!("{f:?}")
    };
    if let Some((mantissa, exponent)) = raw.split_once('e') {
        let exp: i32 = exponent.parse()?;
        return Ok(format!(
            "{mantissa}e{}{exp:02}",
            if exp >= 0 { "+" } else { "-" },
            exp = exp.abs()
        ));
    }
    Ok(raw)
}
fn s<'a>(v: &'a Value, key: &str) -> &'a str {
    v.get(key).and_then(Value::as_str).unwrap_or("")
}
fn sd<'a>(v: &'a Value, key: &str, default: &'a str) -> &'a str {
    v.get(key).and_then(Value::as_str).unwrap_or(default)
}
fn q(v: &Value, key: &str) -> String {
    lua_str(s(v, key))
}
fn qd(v: &Value, key: &str, default: &str) -> String {
    lua_str(sd(v, key, default))
}
fn n(v: &Value, key: &str, default: Value) -> String {
    lua_num(v.get(key).unwrap_or(&default)).expect("validated numeric field")
}
fn b(v: &Value, key: &str, default: bool) -> bool {
    v.get(key).and_then(Value::as_bool).unwrap_or(default)
}
fn arr<'a>(v: &'a Value, key: &str) -> &'a [Value] {
    v.get(key)
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[])
}
fn truth(v: &Value, key: &str) -> bool {
    match &v[key] {
        Value::Null => false,
        Value::String(x) => !x.is_empty(),
        Value::Bool(x) => *x,
        Value::Array(x) => !x.is_empty(),
        Value::Object(x) => !x.is_empty(),
        Value::Number(x) => x.as_f64() != Some(0.),
    }
}
fn has(v: &Value, key: &str) -> bool {
    v.get(key).is_some()
}
fn val(v: &Value) -> String {
    if let Some(s) = v.as_str() {
        lua_str(s)
    } else {
        lua_num(v).expect("validated scalar")
    }
}
fn pystr(v: &Value) -> String {
    match v {
        Value::String(x) => x.clone(),
        Value::Bool(true) => "True".into(),
        Value::Bool(false) => "False".into(),
        Value::Null => "None".into(),
        _ => v.to_string(),
    }
}
fn call(name: &str, args: &[String]) -> String {
    format!("\t{name}({})", args.join(", "))
}
fn wait(n: String) -> String {
    call("wait", &[n])
}
fn load(c: &str) -> String {
    format!("\trunwait(characters.LoadCharacterAsset({c}))")
}
fn ret(id: &str) -> String {
    format!("\t\treturn node_{id}()")
}
struct Context<'a> {
    mod_id: &'a str,
    script_id: &'a str,
    mood: bool,
    next: &'a str,
    content_root: &'a Path,
}
fn check(expr: String, node: &Value) -> Vec<String> {
    vec![
        format!("\tif {expr} then"),
        ret(s(node, "success")),
        "\telse".into(),
        ret(s(node, "failure")),
        "\tend".into(),
    ]
}
fn condition(node: &Value) -> String {
    let expr = if s(node, "source") == "mod" {
        format!("modflags[{}]", q(node, "key"))
    } else {
        format!("checkpointmanager.Condition({})", q(node, "key"))
    };
    if b(node, "invert", false) {
        format!("not ({expr})")
    } else {
        expr
    }
}
fn item_api(kind: &str) -> &'static str {
    match kind {
        "book" => "Book",
        "misc" => "Misc",
        _ => "Special",
    }
}
fn reward(entries: &[Value]) -> Vec<String> {
    let mut out = Vec::new();
    for e in entries {
        let key = q(e, "key");
        let amount = n(e, "amount", json!(0));
        match s(e, "kind") {
            "stat" => {
                out.push(call(
                    "statmodifymanager.Player",
                    &[key.clone(), amount, "\"\"".into(), "1".into()],
                ));
                out.push(format!("\twait(statmodifymanager.GetDisplayTime({key}))"));
            }
            "affinity" => out.push(call(
                "statmodifymanager.Character",
                &[key, amount, "1".into()],
            )),
            "talent" => out.push(call("statmodifymanager.AddTalent", &[key, amount])),
            "item" => out.push(call(
                &format!("statmodifymanager.Add{}", item_api(s(e, "category"))),
                &[key, amount],
            )),
            _ => {
                out.push(call("statmodifymanager.AddStory", &[key.clone()]));
                out.push(format!("\tmodflags[{key}] = true"));
            }
        }
    }
    out
}
fn gameplay_config(node: &Value, scalar: &[&str], lists: &[(&str, &[&str])]) -> String {
    let mut parts: Vec<String> = scalar
        .iter()
        .filter(|k| has(node, k) && !node[**k].is_null() && node[**k] != "")
        .map(|k| {
            format!(
                "{k}={}",
                if let Some(b) = node[*k].as_bool() {
                    if b {
                        "1".into()
                    } else {
                        "0".into()
                    }
                } else {
                    pystr(&node[*k])
                }
            )
        })
        .collect();
    for (field, columns) in lists {
        if has(node, field) {
            let rows: Vec<String> = arr(node, field)
                .iter()
                .map(|item| {
                    if item.is_string() && *columns == ["id"] {
                        return item.as_str().unwrap().to_owned();
                    }
                    columns
                        .iter()
                        .map(|k| item.get(*k).map(pystr).unwrap_or_default())
                        .collect::<Vec<_>>()
                        .join(":")
                })
                .collect();
            parts.push(format!("{field}={}", rows.join(",")));
        }
    }
    parts.join(";")
}
fn emit(node: &Value, ctx: &Context<'_>) -> Result<Vec<String>> {
    let mut out = Vec::new();
    let kind = s(node, "type");
    let c = q(node, "character");
    let user = s(node, "character").starts_with("user:");
    match kind {
        "music" => match sd(node, "op", "play") {
            "stop" => out.push("\tluamanager.StopMusic()".into()),
            "fadeout" => {
                let d = n(node, "seconds", json!(2));
                out.push(call("luamanager.FadeOutMusic", &[d.clone()]));
                out.push(wait(d));
            }
            _ => out.push(call("luamanager.PlayMusic", &[q(node, "name")])),
        },
        "sound" => {
            if sd(node, "op", "play") == "fadeout" {
                let d = n(node, "seconds", json!(1));
                out.push(call("luamanager.FadeOutEnvSound", &[d.clone()]));
                out.push(wait(d));
            } else {
                out.push(call(
                    if sd(node, "kind", "sound") == "env" {
                        "luamanager.PlayEnvSound"
                    } else {
                        "luamanager.PlaySound"
                    },
                    &[q(node, "name")],
                ));
            }
        }
        "scene" => {
            out.extend([
                "\tmod_background_clear(0)".into(),
                "\trunblock(flowcharts.view, \"out\")".into(),
            ]);
            let view = s(node, "view");
            if view != "out" {
                if !["black", "white"].contains(&view) {
                    out.push(format!("\trunwait(flowcharts.LoadView({}))", lua_str(view)));
                }
                out.push(format!(
                    "\tgetvar(flowcharts.view, \"ViewName\").value = {}",
                    lua_str(view)
                ));
                out.push("\trunblock(flowcharts.view, \"view\")".into());
            }
        }
        "background" | "custom_cg" | "overlay" => {
            let action = s(node, "action");
            let fade = if kind == "background" && ["set", "clear"].contains(&action) {
                "0".into()
            } else {
                n(
                    node,
                    "fade",
                    json!(if kind == "overlay" { 0.25 } else { 0.5 }),
                )
            };
            out.push(match kind {
                "background" => {
                    if ["fadeout", "clear"].contains(&action) {
                        call("mod_background_clear", &[fade.clone()])
                    } else {
                        call("mod_background_show", &[q(node, "image"), fade.clone()])
                    }
                }
                "custom_cg" => {
                    if action == "hide" {
                        call("mod_cg_hide", &[fade.clone()])
                    } else {
                        call(
                            "mod_cg_show",
                            &[
                                q(node, "image"),
                                fade.clone(),
                                n(node, "scale", json!(100)),
                                n(node, "x", json!(0)),
                                n(node, "y", json!(0)),
                            ],
                        )
                    }
                }
                _ => {
                    if action == "hide" {
                        call("mod_overlay_hide", &[q(node, "slot"), fade.clone()])
                    } else {
                        call(
                            "mod_overlay_show",
                            &[
                                q(node, "slot"),
                                q(node, "image"),
                                qd(node, "position", "center"),
                                n(node, "scale", json!(100)),
                                n(node, "opacity", json!(100)),
                                qd(node, "layer", "front"),
                                fade.clone(),
                            ],
                        )
                    }
                }
            });
            if fade.parse::<f64>()? > 0. {
                out.push(wait(fade));
            }
        }
        "show" => {
            let portrait = qd(node, "portrait", "normal");
            let facing = qd(node, "facing", "right");
            let pos = q(node, "position");
            let fade = n(node, "fadeDuration", json!(0));
            let duration = n(node, "moveDuration", json!(0));
            if truth(node, "appearance") {
                out.push(call("mod_player_appearance", &[q(node, "appearance")]));
            }
            if user {
                out.push(call(
                    "mod_char_show",
                    &[c.clone(), portrait, pos, facing, fade, duration],
                ));
                out.push(call("mod_char_focus", &[c]));
            } else {
                out.push(load(&c));
                out.push(call(
                    "characters.LoadCharacterPortrait",
                    &[c.clone(), portrait.clone()],
                ));
                out.push(format!("\tstage.show{{character=characters.Get({c}), portrait=characters.GetPortrait({c}, {portrait}), fromPosition={pos}, toPosition={pos}, facing={facing}, fadeDuration={fade}, moveDuration={duration}, useDefaultSettings=false}}"));
                out.push(call("characters.Focus", &[c]));
            }
            if !ctx.mood {
                out.push("\tmod_hide_mood()".into());
            }
        }
        "move" => {
            let from = q(node, "from");
            let to = q(node, "to");
            let duration = n(node, "duration", json!(1));
            if user {
                out.push(call("mod_char_move", &[c, from, to, duration.clone()]));
            } else {
                out.push(load(&c));
                out.push(format!("\tstage.show{{character=characters.Get({c}), fromPosition={from}, toPosition={to}, moveDuration={duration}, useDefaultSettings=false}}"));
            }
            out.push(wait(duration));
        }
        "face" => {
            let facing = q(node, "facing");
            if user {
                out.push(call("mod_char_face", &[c, facing]));
            } else {
                out.push(load(&c));
                out.push(format!("\tstage.show{{character=characters.Get({c}), facing={facing}, useDefaultSettings=false}}"));
            }
        }
        "hide" => {
            let fade = n(node, "fadeDuration", json!(0));
            if user {
                out.push(call("mod_char_hide", &[c, fade]));
            } else {
                out.push(load(&c));
                out.push(format!("\tstage.hide{{character=characters.Get({c}), fadeDuration={fade}, useDefaultSettings=false}}"));
            }
        }
        "focus" => {
            if !user {
                out.push(load(&c));
            }
            out.push(call(
                if user {
                    "mod_char_focus"
                } else {
                    "characters.Focus"
                },
                &[c],
            ));
        }
        "offset" | "rotate" => {
            let d = n(node, "duration", json!(0));
            let mut args = vec![c.clone()];
            if kind == "offset" {
                args.extend([n(node, "x", json!(0)), n(node, "y", json!(0))]);
            } else {
                args.push(n(node, "angle", json!(0)));
            }
            args.push(d.clone());
            if user {
                out.push(call(
                    if kind == "offset" {
                        "mod_char_offset"
                    } else {
                        "mod_char_rotate"
                    },
                    &args,
                ));
                out.push(wait(d));
            } else {
                out.push(load(&c));
                if kind == "offset" {
                    out.push(format!(
                        "\trunwait(characters.MoveOffsetCoroutine({}))",
                        args.join(", ")
                    ));
                } else {
                    out.push(call("characters.Rotate", &args));
                }
            }
        }
        "say" => {
            let mode = sd(node, "mode", "character");
            let voice = s(node, "voice");
            let voiced = !voice.trim().is_empty();
            out.push(if voiced {
                call("mod_play_voice", &[lua_str(voice)])
            } else {
                "\tmod_stop_voice()".into()
            });
            let say = format!(
                "\tsay(luamanager.GetStoryText({}))",
                lua_str(&format!(
                    "MOD_{}_{}_{}",
                    if ctx.mod_id.is_empty() {
                        "MOD"
                    } else {
                        ctx.mod_id
                    },
                    ctx.script_id,
                    s(node, "id")
                ))
            );
            if ["narrative", "center"].contains(&mode) {
                out.extend([
                    format!("\tsetsaydialog(saydialogs.{mode})"),
                    "\tsayoptions.waitforinput = true".into(),
                    "\tsayoptions.fadewhendone  = true".into(),
                    "\tsetcharacter(narrative)".into(),
                ]);
            } else {
                let p = qd(node, "portrait", "normal");
                if !user {
                    out.push(load(&c));
                }
                out.push(format!("\tsetsaydialog(saydialogs.{mode})"));
                out.push(call(
                    if user {
                        "mod_char_portrait"
                    } else {
                        "characters.LoadCharacterPortrait"
                    },
                    &[c.clone(), p.clone()],
                ));
                out.extend([
                    "\tsayoptions.waitforinput = true".into(),
                    "\tsayoptions.fadewhendone  = true".into(),
                ]);
                if user {
                    out.push(call("mod_char_set_speaker", &[c.clone()]));
                } else {
                    out.push(format!("\tstage.showPortrait(characters.Get({c}), characters.GetPortrait({c}, {p}))"));
                    out.push(format!(
                        "\tsetcharacter(characters.Get({c}), characters.GetPortrait({c}, {p}))"
                    ));
                }
                if mode == "think" {
                    out.extend([
                        "\tos_mask.SetLastPosition()".into(),
                        "\tos_mask.Show(true)".into(),
                    ]);
                }
                out.push(call(
                    if user {
                        "mod_char_focus"
                    } else {
                        "characters.Focus"
                    },
                    &[c],
                ));
            }
            if !ctx.mood {
                out.push("\tmod_hide_mood()".into());
            }
            out.push(say);
            if !ctx.mood {
                out.push("\tmod_hide_mood()".into());
            }
            if mode == "think" {
                out.push("\tos_mask.Show(false)".into());
            }
            if voiced {
                out.push("\tmod_stop_voice()".into());
            }
        }
        "choice" => {
            let dialog = sd(node, "dialog", "Options");
            out.extend([
                format!("\tsetmenudialog(menudialogs.{dialog})"),
                "\tlocal option1 = {}".into(),
            ]);
            for (i, opt) in arr(node, "options").iter().enumerate() {
                out.push(format!("\toption1[{}] = {}", i + 1, q(opt, "text")));
            }
            out.extend([
                "\tlocal choice1 = choose(option1)".into(),
                format!("\tmenudialogs.{dialog}.SetActive(false)"),
            ]);
            for (i, opt) in arr(node, "options").iter().enumerate() {
                out.push(format!(
                    "\t{} choice1 == {} then",
                    if i == 0 { "if" } else { "elseif" },
                    i + 1
                ));
                out.push(ret(s(opt, "goto")));
            }
            out.push("\tend".into());
        }
        "shock" => {
            let d = n(node, "duration", json!(0.5));
            if user {
                out.push(call("mod_char_shock", &[c, d.clone()]));
                out.push(wait(d));
            } else {
                out.push(load(&c));
                out.push(format!("\tgetvar(flowcharts.common, \"ShockPosition\").value = characters.Get({c}).State.holder.gameObject"));
                out.push(format!(
                    "\tgetvar(flowcharts.common, \"ShockDuration\").value = {d}"
                ));
                out.push("\trunblock(flowcharts.common, \"shock\")".into());
            }
        }
        "mask" => out.push(format!("\tos_mask.Show({})", b(node, "show", false))),
        "intro" => {
            let source = sd(node, "intro_source", "official");
            if source == "official" {
                out.push(format!("\trunwait(intropanel.Show({c}))"));
            } else {
                let intro;
                if source == "character" {
                    let id = crate::content::parse_content_ref(s(node, "character"))?.ok_or_else(
                        || anyhow::anyhow!("intro 的 character 必须是 user: 角色引用"),
                    )?;
                    let (meta, _) =
                        crate::content::resolve_content(ctx.content_root, "character", &id)?;
                    if !meta["intro"].is_object() {
                        bail!(
                            "自定义角色 user:{id} 还没有介绍卡。请先在用户内容库的角色「介绍卡」页填写。"
                        );
                    }
                    let mut x = meta["intro"].clone();
                    x["image"] = json!(if s(&x, "image").is_empty() {
                        String::new()
                    } else {
                        format!(
                            "{}/{}",
                            crate::content::package_content_dir("character", &id)?,
                            s(&x, "image")
                        )
                    });
                    intro = x;
                } else {
                    intro = node.clone();
                }
                out.push(call(
                    "mod_prepare_character_intro",
                    &[
                        q(&intro, "title"),
                        q(&intro, "name"),
                        q(&intro, "text"),
                        q(&intro, "image"),
                        n(&intro, "image_scale", json!(100)),
                        n(&intro, "image_x", json!(0)),
                        n(&intro, "image_y", json!(0)),
                    ],
                ));
                out.push("\trunwait(intropanel.Show(\"__lommod_custom_intro__\"))".into());
            }
        }
        "effect" => {
            let play = if has(node, "play") {
                if b(node, "play", false) { "1" } else { "0" }.into()
            } else {
                n(node, "d", json!(1))
            };
            out.push(call(
                "effects.SetupEffect",
                &[
                    q(node, "name"),
                    n(node, "x", json!(0)),
                    n(node, "y", json!(0)),
                    n(node, "a", json!(1)),
                    n(node, "b", json!(1)),
                    n(node, "c", json!(1)),
                    play,
                ],
            ));
        }
        "transition" => out.push(format!(
            "\trunwait(transitionblack.{}({}))",
            if s(node, "phase") == "in" {
                "TransitionIn"
            } else {
                "TransitionOut"
            },
            qd(node, "dir", "lr")
        )),
        "camera" => out.push(call(
            "maincamera.ActiveVolume",
            &[
                q(node, "name"),
                if b(node, "active", false) { "1" } else { "0" }.into(),
            ],
        )),
        "block" => {
            let fc = format!("flowcharts.{}", s(node, "flowchart"));
            for v in arr(node, "vars") {
                out.push(format!(
                    "\tgetvar({fc}, {}).value = {}",
                    q(v, "name"),
                    val(&v["value"])
                ));
            }
            out.push(call("runblock", &[fc, q(node, "name")]));
        }
        "cg" => {
            let name = match s(node, "kind") {
                "picture" => "Picture",
                "item" => "ItemPicture",
                "big" => "BigPicture",
                "map" => "Map",
                "family" => "FamilyTree",
                _ => "Title",
            };
            if s(node, "action") == "hide" {
                out.push(format!("\trunwait(mainui.Hide{name}())"));
            } else {
                let fields: &[&str] = match s(node, "kind") {
                    "map" => &["key", "key2"],
                    "family" => &["key", "key2", "n1", "n2"],
                    _ => &["key"],
                };
                let args = fields
                    .iter()
                    .map(|k| val(&node[*k]))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push(if name == "Title" {
                    format!("\tmainui.DisplayTitle({args})")
                } else {
                    format!("\trunwait(mainui.Show{name}({args}))")
                });
            }
        }
        "dim" => {
            let dim = b(node, "dimmed", false);
            if user {
                out.push(format!("\tmod_char_dim({c}, {dim})"));
            } else {
                out.push(load(&c));
                out.push(format!("\tstage.SetDimmed(characters.Get({c}), {dim})"));
            }
        }
        "message" => out.push(call("mainui.DisplayMessageText", &[q(node, "text")])),
        "dayenv" => out.push(call(
            "luamanager.SetGameDayEnvironment",
            &[n(node, "day_type", json!(1))],
        )),
        "stat" => {
            let k = q(node, "key");
            out.push(call(
                "statmodifymanager.Player",
                &[
                    k.clone(),
                    n(node, "delta", json!(0)),
                    q(node, "mode"),
                    n(node, "display", json!(1)),
                ],
            ));
            if b(node, "waitDisplay", true) {
                out.push(format!("\twait(statmodifymanager.GetDisplayTime({k}))"));
            }
        }
        "stat_set" => out.push(call(
            if b(node, "update", false) {
                "statmodifymanager.UpdateSetPlayerStat"
            } else {
                "statmodifymanager.SetPlayer"
            },
            &[q(node, "key"), n(node, "value", json!(0))],
        )),
        "affinity" => out.push(call(
            "statmodifymanager.Character",
            &[c, n(node, "delta", json!(0)), "1".into()],
        )),
        "talent" => out.push(call(
            "statmodifymanager.AddTalent",
            &[q(node, "talent"), n(node, "level", json!(0))],
        )),
        "item" => {
            let api = item_api(s(node, "kind"));
            if b(node, "remove", false) {
                out.push(call(
                    &format!("statmodifymanager.Remove{api}"),
                    &[q(node, "item")],
                ));
            } else {
                out.push(call(
                    &format!("statmodifymanager.Add{api}"),
                    &[q(node, "item"), n(node, "count", json!(1))],
                ));
            }
        }
        "flag" => {
            let f = q(node, "flag");
            out.push(call("statmodifymanager.AddStory", &[f.clone()]));
            out.push(format!("\tmodflags[{f}] = true"));
        }
        "game_flag" => out.push(call(
            if sd(node, "op", "set") == "add" {
                "statmodifymanager.AddFlag"
            } else {
                "statmodifymanager.SetFlag"
            },
            &[q(node, "flag"), n(node, "value", json!(0))],
        )),
        "enemy" => {
            let op = s(node, "op");
            if op == "id" {
                out.push(call("statmodifymanager.ModifyEnemyId", &[q(node, "enemy")]));
            } else {
                out.push(call(
                    &format!(
                        "statmodifymanager.ModifyEnemy{}",
                        match op {
                            "team" => "Team",
                            "level" => "Level",
                            _ => "People",
                        }
                    ),
                    &[
                        q(node, "enemy"),
                        n(node, "value", json!(0)),
                        n(node, "display", json!(1)),
                    ],
                ));
            }
        }
        "battle_skill" => {
            let op = s(node, "op");
            if op == "reset" {
                out.push("\tluamanager.ResetBattleSkill()".into());
            } else {
                let (api, field, default) = match op {
                    "active" => ("SetBattleSkillActive", "active", 1),
                    "level" => ("SetBattleSkillLevel", "level", 1),
                    _ => ("SetPlayerBattleSkill", "index", 2),
                };
                out.push(call(
                    &format!("luamanager.{api}"),
                    &[q(node, "key"), n(node, field, json!(default))],
                ));
            }
        }
        "combat" | "battle" => {
            let mut config = node.clone();
            let encoded = if kind == "combat" {
                if !has(&config, "background") {
                    config["background"] = json!("center");
                }
                gameplay_config(
                    &config,
                    &[
                        "character",
                        "background",
                        "max_health",
                        "health",
                        "max_stamina",
                        "stamina",
                        "stamina_power",
                        "strength",
                        "internal",
                        "dexterity",
                        "talking",
                        "defence",
                        "sword",
                        "fist",
                        "martial_weapon",
                        "mental",
                        "weapon_poison_value",
                        "weapon_paralyzed_value",
                        "poison_resist",
                        "paralyzed_resist",
                        "disposition",
                        "behaviour",
                        "karma",
                        "training",
                        "attack_damage_addition",
                        "defence_addition",
                        "ultimate_damage_rate",
                        "attack_dice_addition",
                        "weapon_damage_addition",
                        "weapon_dice_addition",
                        "weapon_hit_addition",
                        "attack_parry_addition",
                        "block_dodge_addition",
                        "block_parry_addition",
                        "talk_rate",
                        "attack_rate",
                        "weapon_rate",
                        "ultimate_rate",
                        "block_rate",
                        "player_max_health",
                        "player_health",
                        "player_max_stamina",
                        "player_stamina",
                        "player_stamina_power",
                        "player_strength",
                        "player_internal",
                        "player_dexterity",
                        "player_talking",
                        "player_defence",
                        "player_sword",
                        "player_fist",
                        "player_martial_weapon",
                        "player_mental",
                        "player_poison_resist",
                        "player_paralyzed_resist",
                        "player_disposition",
                        "player_behaviour",
                        "player_karma",
                        "player_training",
                    ],
                    &[
                        ("talents", &["key", "level"]),
                        ("player_talents", &["key", "level"]),
                    ],
                )
            } else {
                gameplay_config(
                    node,
                    &["title", "friend_health", "enemy_health"],
                    &[
                        ("friend_factions", &["id", "people"]),
                        ("enemy_factions", &["id", "people"]),
                        ("friend_characters", &["id"]),
                        ("enemy_characters", &["id"]),
                    ],
                )
            };
            out.push(call(
                "mod_gameplay_prepare",
                &[
                    lua_str(kind),
                    lua_str(ctx.script_id),
                    q(node, "id"),
                    q(node, "win"),
                    q(node, "lose"),
                ],
            ));
            out.push(call(
                "mod_gameplay_configure",
                &[lua_str(kind), lua_str(&encoded)],
            ));
            out.extend([
                "\tmod_stop_voice()".into(),
                "\tmod_hide_all()".into(),
                call("mod_gameplay_start_scene", &[lua_str(kind)]),
            ]);
        }
        "battle_result" => {
            let kind = sd(node, "kind", "any");
            out.push(format!(
                "\tlocal gameplay_result = mod_gameplay_last_result({}, {})",
                lua_str(ctx.script_id),
                lua_str(if kind == "any" { "" } else { kind })
            ));
            out.extend([
                format!(
                    "\tif gameplay_result == \"win\" then return node_{}()",
                    s(node, "win")
                ),
                format!(
                    "\telseif gameplay_result == \"lose\" then return node_{}()",
                    s(node, "lose")
                ),
                "\telse error(\"没有可供 battle_result 消费的已验证战斗结果\") end".into(),
            ]);
        }
        "reward" => out = reward(arr(node, "entries")),
        "result_screen" => {
            let message = if truth(node, "text") {
                format!("{}\n{}", s(node, "title"), s(node, "text"))
            } else {
                s(node, "title").into()
            };
            out.push(call("mainui.DisplayMessageText", &[lua_str(&message)]));
            out.extend(reward(arr(node, "entries")));
        }
        "custom_shop" => {
            out.push("\tmod_custom_shop_begin()".into());
            for item in arr(node, "items") {
                let add = call(
                    "mod_custom_shop_add",
                    &[
                        q(item, "category"),
                        q(item, "item"),
                        n(item, "count", json!(1)),
                    ],
                );
                if truth(item, "condition") {
                    out.extend([
                        format!("\tif {} then", condition(&item["condition"])),
                        format!("\t{add}"),
                        "\tend".into(),
                    ]);
                } else {
                    out.push(add);
                }
            }
            out.push(format!(
                "\trunwait(shoppanel.Open({}))",
                n(node, "discount", json!(0))
            ));
            out.push("\tmod_custom_shop_end()".into());
        }
        "stat_check" | "affinity_check" | "talent_check" | "persistent_check" => {
            let expr = match kind {
                "stat_check" => format!("luamanager.GetStatData({}, 1)", q(node, "key")),
                "affinity_check" => format!("mod_affinity_value({c})"),
                "talent_check" => format!("mod_talent_level({})", q(node, "talent")),
                _ => format!("mod_persistent_get({})", q(node, "key")),
            };
            out = check(
                format!("{expr} {} {}", s(node, "op"), n(node, "value", json!(0))),
                node,
            );
        }
        "item_check" => {
            let mut expr = format!("mod_has_item({}, {})", q(node, "category"), q(node, "item"));
            if b(node, "invert", false) {
                expr = format!("not ({expr})");
            }
            out = check(expr, node);
        }
        "flag_check" => {
            let source = s(node, "source");
            let mut expr = match source {
                "mod" => format!("modflags[{}]", q(node, "flag")),
                "condition" => format!("checkpointmanager.Condition({})", q(node, "flag")),
                _ => format!(
                    "tonumber(luamanager.GetFlagData({})) {} {}",
                    q(node, "flag"),
                    s(node, "op"),
                    n(node, "value", json!(0))
                ),
            };
            if source != "flag_value" && b(node, "invert", false) {
                expr = format!("not ({expr})");
            }
            out = check(expr, node);
        }
        "activity" => {
            if truth(node, "message") {
                out.push(call("mainui.DisplayMessageText", &[q(node, "message")]));
            }
            match s(node, "time") {
                "round" => out.push("\tluamanager.NextRound()".into()),
                "month" => out.push("\tluamanager.NextMonth()".into()),
                _ => (),
            };
            out.push(format!(
                "\tif luamanager.GetStatData({}, 1) {} {} then",
                q(node, "stat"),
                s(node, "op"),
                n(node, "value", json!(0))
            ));
            out.extend(
                reward(arr(node, "success_rewards"))
                    .iter()
                    .map(|x| format!("\t{x}")),
            );
            out.push(ret(s(node, "success")));
            out.push("\telse".into());
            out.extend(
                reward(arr(node, "failure_rewards"))
                    .iter()
                    .map(|x| format!("\t{x}")),
            );
            out.push(ret(s(node, "failure")));
            out.push("\tend".into());
        }
        "mod_quest" => {
            if truth(node, "message") {
                out.push(call("mainui.DisplayMessageText", &[q(node, "message")]));
            }
            out.push(call("mod_quest_set", &[q(node, "quest"), q(node, "op")]));
        }
        "quest_check" => {
            out = check(
                format!(
                    "mod_quest_state({}) == {}",
                    q(node, "quest"),
                    q(node, "state")
                ),
                node,
            )
        }
        "persistent_var" => out.push(call(
            if s(node, "op") == "set" {
                "mod_persistent_set"
            } else {
                "mod_persistent_add"
            },
            &[q(node, "key"), n(node, "value", json!(0))],
        )),
        "mission" => out.push(call(
            "statmodifymanager.Mission",
            &[q(node, "name"), q(node, "key")],
        )),
        "time" => match s(node, "op") {
            "round" => out.push("\tluamanager.NextRound()".into()),
            "month" => out.push("\tluamanager.NextMonth()".into()),
            op => {
                let mut args = Vec::new();
                if op == "mission" {
                    args.push(q(node, "name"));
                }
                args.extend([
                    n(node, "year", json!(0)),
                    n(node, "month", json!(0)),
                    n(node, "stage", json!(0)),
                ]);
                out.push(call(
                    if op == "mission" {
                        "luamanager.SetMissionTime"
                    } else {
                        "luamanager.SetGameTime"
                    },
                    &args,
                ));
            }
        },
        "autosave" => {
            out.push(
                match sd(node, "kind", "story") {
                    "free" => "\tluamanager.AutoFreeSave()",
                    "prologue" => "\tluamanager.PrologueSave(0)",
                    _ => "\tluamanager.AutoSave()",
                }
                .into(),
            );
            if has(node, "save_button") {
                out.push(call(
                    "luamanager.ToggleSaveButton",
                    &[n(node, "save_button", json!(0))],
                ));
            }
        }
        "branch" => {
            let source = sd(node, "source", "mod");
            let cases = arr(node, "cases");
            let flag = q(node, "flag");
            if ["mod", "condition"].contains(&source) {
                let target = |num| {
                    cases
                        .iter()
                        .rev()
                        .find(|c| c["value"].as_i64() == Some(num))
                        .map(|c| s(c, "goto"))
                        .unwrap_or(ctx.next)
                };
                out.extend([
                    format!(
                        "\tif {} then",
                        if source == "mod" {
                            format!("modflags[{flag}]")
                        } else {
                            format!("checkpointmanager.Condition({flag})")
                        }
                    ),
                    ret(target(1)),
                    "\telse".into(),
                    ret(target(2)),
                    "\tend".into(),
                ]);
            } else {
                let expr = match source {
                    "stat" => format!("luamanager.GetStatData({}, 1)", q(node, "stat")),
                    "flag_value" => format!("tonumber(luamanager.GetFlagData({flag}))"),
                    _ => format!("checkpointmanager.Switch({flag})"),
                };
                out.push(format!("\tlocal branch1 = {expr}"));
                for (i, c) in cases.iter().enumerate() {
                    out.push(format!(
                        "\t{} branch1 {} {} then",
                        if i == 0 { "if" } else { "elseif" },
                        if source == "game" {
                            "=="
                        } else {
                            sd(c, "op", ">=")
                        },
                        n(c, "value", json!(0))
                    ));
                    out.push(ret(s(c, "goto")));
                }
                out.extend(["\telse".into(), ret(ctx.next), "\tend".into()]);
            }
        }
        "dice" => out = emit_dice(node)?,
        "goto_scene" => {
            out.extend(["\tmod_stop_voice()".into(), "\tmod_hide_all()".into()]);
            let scene = s(node, "scene");
            if scene == "End" && has(node, "image") {
                out.push(call(
                    "mod_set_ending_text",
                    &[q(node, "title"), q(node, "desc"), q(node, "image")],
                ));
            } else if ["End", "GameOver"].contains(&scene)
                && (has(node, "title") || has(node, "desc"))
            {
                out.push(call(
                    if scene == "End" {
                        "mod_set_ending_text"
                    } else {
                        "mod_set_death_text"
                    },
                    &[q(node, "title"), q(node, "desc")],
                ));
            }
            if scene == "End" {
                let content = ["title", "desc", "image"]
                    .iter()
                    .any(|k| !s(node, k).trim().is_empty());
                out.extend([
                    "\tluamanager.SetEnableActions(0)".into(),
                    format!(
                        "\trunwait(endgamepanel.Open({}))",
                        if content {
                            lua_str("__MORTAL_MOD_END__")
                        } else {
                            q(node, "key")
                        }
                    ),
                    "\tluamanager.SetEnableActions(1)".into(),
                    "\trunwait(transitionblack.TransitionIn(\"lr\"))".into(),
                    "\tluamanager.ChangeScene(\"Title\", \"\", \"\")".into(),
                ]);
            } else {
                out.push(call(
                    "luamanager.ChangeScene",
                    &[
                        lua_str(scene),
                        q(node, "key"),
                        lua_str(if scene == "GameOver" {
                            "Title"
                        } else {
                            sd(node, "next", "Story")
                        }),
                    ],
                ));
            }
        }
        "panel" => out.push(match s(node, "panel") {
            "martial" => format!(
                "\trunwait(martialpanel.Open({}))",
                n(node, "mode", json!(0))
            ),
            "weapon" => "\trunwait(weaponupgradepanel.Open())".into(),
            "poison" => "\trunwait(poisonupgradepanel.Open())".into(),
            "cg" => format!("\trunwait(cgpanel.Open({}))", q(node, "key")),
            "cgvideo" => format!("\trunwait(cgvideopanel.Open({}, 0))", q(node, "key")),
            "shop" => format!(
                "\trunwait(shoppanel.Open({}))",
                n(node, "discount", json!(0))
            ),
            "newshop" => "\tshoppanel.NewShop()".into(),
            "credit" => "\trunwait(creditpanel.Open())".into(),
            _ => format!("\trunwait(endgamepanel.Open({}))", q(node, "key")),
        }),
        "wait" => out.push(wait(n(node, "seconds", json!(0)))),
        "free_trigger" => out.push(format!(
            "\t-- 自由模式触发（声明型节点，运行时不产生指令）：{} → {}",
            s(node, "position"),
            s(node, "script")
        )),
        "end" => {
            out.extend(["\tmod_stop_voice()".into(), "\tmod_hide_all()".into()]);
            if node["next_script"].is_null() {
                out.push("\tluamanager.ChangeScene(\"Free\", \"\", \"\")".into());
            } else {
                let target = if ctx.mod_id.is_empty() {
                    s(node, "next_script").to_string()
                } else {
                    format!("MOD_{}_{}", ctx.mod_id, s(node, "next_script"))
                };
                out.push(call("luamanager.SetNextScript", &[lua_str(&target)]));
                out.push("\tluamanager.Init()".into());
            }
        }
        "death" => {
            let title = if truth(node, "title") {
                s(node, "title")
            } else {
                "勝敗乃兵家常事"
            };
            out.extend([
                "\tmod_stop_voice()".into(),
                "\tmod_hide_all()".into(),
                "\trunblock(flowcharts.view, \"out\")".into(),
                "\tgetvar(flowcharts.view, \"ViewName\").value = \"black\"".into(),
                "\trunblock(flowcharts.view, \"view\")".into(),
                call("mod_set_death_text", &[lua_str(title), q(node, "text")]),
                call(
                    "luamanager.ChangeScene",
                    &[lua_str("GameOver"), q(node, "death_id"), lua_str("Title")],
                ),
            ]);
        }
        "raw" => out = splitlines(s(node, "code")),
        _ => bail!(
            "内部错误：节点 {:?} 类型 {kind:?} 未校验通过",
            s(node, "id")
        ),
    }
    Ok(out)
}
fn splitlines(raw: &str) -> Vec<String> {
    let r = raw.replace("\r\n", "\n").replace(
        [
            '\r', '\u{b}', '\u{c}', '\u{1c}', '\u{1d}', '\u{1e}', '\u{85}', '\u{2028}', '\u{2029}',
        ],
        "\n",
    );
    let mut parts = r.split('\n').map(str::to_owned).collect::<Vec<_>>();
    if r.is_empty() || r.ends_with('\n') {
        parts.pop();
    }
    parts
}
fn editor_data() -> &'static Value {
    static DATA: OnceLock<Value> = OnceLock::new();
    DATA.get_or_init(|| {
        serde_json::from_str(include_str!("../../../data/editor_data.json"))
            .expect("bundled editor data")
    })
}
fn emit_dice(node: &Value) -> Result<Vec<String>> {
    let legacy = has(node, "check");
    let meta = &editor_data()["dice_meta"][s(node, "check")];
    let fallback = json!([{"text":sd(&node["options"][0],"text",""),"cond":""}]);
    let bands = if legacy {
        meta["bands"]
            .as_array()
            .filter(|a| !a.is_empty())
            .unwrap_or(fallback.as_array().unwrap())
            .as_slice()
    } else {
        arr(node, "bands")
    };
    let maximum = if legacy {
        n(meta, "max", json!(99))
    } else {
        n(node, "max", json!(99))
    };
    let check_name = if legacy {
        q(node, "check")
    } else {
        lua_str("__lom_mod_custom")
    };
    let mut out = Vec::new();
    if !legacy {
        let thresholds = bands[..bands.len() - 1]
            .iter()
            .map(|b| pystr(&b["upper"]))
            .collect::<Vec<_>>()
            .join(",");
        out.push(call(
            "mod_dice_prepare",
            &[
                maximum.clone(),
                q(node, "header"),
                lua_str(&thresholds),
                n(node, "bonus", json!(0)),
                q(node, "bonus_name"),
                q(node, "bonus_status"),
            ],
        ));
    }
    out.extend([
        "\tsetmenudialog(menudialogs.Dice)".into(),
        format!(
            "\tlocal dice_rand1 = math.random({}{maximum})",
            if legacy { "" } else { "0, " }
        ),
        format!("\tdicemenudialog.SetRandom({maximum}, dice_rand1)"),
        format!("\tlocal dice_result1 = checkpointmanager.Dice({check_name}, dice_rand1)"),
        "\tlocal dice_opts1 = {}".into(),
    ]);
    let texts = arr(&node["options"][0], "band_texts");
    for (i, band) in bands.iter().enumerate() {
        let text = if legacy && texts.len() == bands.len() {
            pystr(&texts[i])
        } else {
            s(band, "text").into()
        }
        .replace('|', "｜");
        let condition = if legacy {
            s(band, "cond").into()
        } else if i + 1 < bands.len() {
            format!("≤ {}", pystr(&band["upper"]))
        } else {
            format!("> {}", pystr(&bands[bands.len() - 2]["upper"]))
        };
        out.push(format!(
            "\tdice_opts1[{}] = {}",
            i + 1,
            lua_str(&format!("{text}|{condition}"))
        ));
    }
    out.extend(["\tdicemenudialog.Setup(dice_result1.ResultCount, dice_result1.Result, dice_result1.Header, dice_result1.Additions)".into(),format!("\trunwait(dicemenudialog.ExecuteRoll(dice_opts1, 1, {check_name}))"),"\tlocal dice_sel1 = dicemenudialog.ResultSelection".into()]);
    if !legacy {
        out.push("\tmod_dice_clear()".into());
    }
    let ranks = band_rank(bands);
    let target = |i: usize| -> &str {
        if !legacy {
            return s(&bands[i], "goto");
        }
        let field = if ranks[i] == 1 {
            "goto_失败"
        } else if ranks[i] == bands.len() && bands.len() >= 3 {
            "goto_大成功"
        } else {
            "goto_成功"
        };
        s(&node["options"][0], field)
    };
    out.push("\tif dice_sel1 == 1 then".into());
    out.push(ret(target(0)));
    for i in 1..bands.len().saturating_sub(1) {
        out.push(format!("\telseif dice_sel1 == {} then", i + 1));
        out.push(ret(target(i)));
    }
    out.extend([
        "\telse".into(),
        ret(target(bands.len() - 1)),
        "\tend".into(),
    ]);
    Ok(out)
}
fn band_rank(bands: &[Value]) -> Vec<usize> {
    let re = regex::Regex::new(r"(<=|>=|<|>|=)\s*(\d+)").unwrap();
    let parsed = bands
        .iter()
        .map(|b| {
            re.captures(s(b, "cond")).map(|c| {
                (
                    c[2].parse::<i64>().unwrap_or(0),
                    [">", ">=", "="].contains(&&c[1]),
                )
            })
        })
        .collect::<Vec<_>>();
    let mut order = (0..bands.len()).collect::<Vec<_>>();
    order.sort_by_key(|i| parsed[*i].unwrap_or((-1, false)));
    let mut ranks = vec![0; bands.len()];
    for (rank, i) in order.into_iter().enumerate() {
        ranks[i] = rank + 1;
    }
    ranks
}
const NO_FLOW: &[&str] = &[
    "end",
    "choice",
    "branch",
    "dice",
    "goto_scene",
    "death",
    "combat",
    "battle",
    "battle_result",
    "stat_check",
    "affinity_check",
    "item_check",
    "talent_check",
    "flag_check",
    "activity",
    "quest_check",
    "persistent_check",
];
/// Compile only after validation; warnings retain their position before the generated header.
pub fn compile_story(
    story: &Value,
    mod_info: Option<&Value>,
    source: Option<&str>,
    content_root: Option<&Path>,
) -> Result<String> {
    let warnings = crate::validate::validate_story(story)?;
    let lua = story_to_lua(story, mod_info, source, content_root)?;
    if warnings.is_empty() {
        Ok(lua)
    } else {
        Ok(format!(
            "{}\n{lua}",
            warnings
                .iter()
                .map(|w| format!("-- lomc 警告：{}", w.replace('\n', " ")))
                .collect::<Vec<_>>()
                .join("\n")
        ))
    }
}
pub fn story_to_lua(
    story: &Value,
    mod_info: Option<&Value>,
    source: Option<&str>,
    content_root: Option<&Path>,
) -> Result<String> {
    let default_root = crate::content::default_repository_root();
    let root = content_root.unwrap_or(&default_root);
    let empty = json!({});
    let info = mod_info.unwrap_or(&empty);
    let nodes = arr(story, "nodes");
    let id = s(story, "id");
    let fallback = format!("story/{id}.json");
    let src = source.filter(|x| !x.is_empty()).unwrap_or(&fallback);
    let mood = b(story, "mood", false);
    let mut lines = vec![
        GENERATED_MARK.to_owned(),
        format!("-- Source: {src} (id={id}, title={})", s(story, "title")),
    ];
    if mod_info.is_some() && info.as_object().is_some_and(|v| !v.is_empty()) {
        lines.push(format!(
            "-- Mod: {} ({}) v{} by {}",
            s(info, "id"),
            s(info, "name"),
            s(info, "version"),
            s(info, "author")
        ));
    }
    lines.extend([
        "".into(),
        "-- mod 内剧情 flag 表（不存档，重进游戏清零）".into(),
        "modflags = modflags or {}".into(),
        format!("mod_set_mood({mood})"),
        "mod_hide_all()".into(),
        "".into(),
        "-- 节点函数前向声明（支持任意 goto / 分支回环）".into(),
        format!(
            "local {}",
            nodes
                .iter()
                .map(|n| format!("node_{}", s(n, "id")))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        "".into(),
    ]);
    for (i, node) in nodes.iter().enumerate() {
        let nid = s(node, "id");
        let kind = s(node, "type");
        let next = nodes.get(i + 1).map(|n| s(n, "id")).unwrap_or("");
        let ctx = Context {
            mod_id: s(info, "id"),
            script_id: id,
            mood,
            next,
            content_root: root,
        };
        lines.extend([
            format!("-- [{nid}] {kind}"),
            format!("node_{nid} = function()"),
            format!(
                "\tif mod_trace_node then mod_trace_node({}, {}) end",
                lua_str(nid),
                lua_str(kind)
            ),
        ]);
        lines.extend(emit(node, &ctx)?);
        if !NO_FLOW.contains(&kind) {
            let target = if node["goto"].is_null() {
                next
            } else {
                s(node, "goto")
            };
            if !target.is_empty() {
                lines.push(format!("\treturn node_{target}()"));
            }
        }
        lines.extend(["end".into(), "".into()]);
    }
    if nodes
        .iter()
        .any(|n| ["combat", "battle"].contains(&s(n, "type")))
    {
        lines.extend([
            "-- 原版战斗返回 Story 后，由 Host 一次性消费已记录的结果目标。".into(),
            format!(
                "local mod_resume_target = mod_gameplay_consume_resume({})",
                lua_str(id)
            ),
            "if mod_resume_target ~= nil and mod_resume_target ~= \"\" then".into(),
        ]);
        for (i, node) in nodes.iter().enumerate() {
            lines.push(format!(
                "\t{} mod_resume_target == {} then return node_{}()",
                if i == 0 { "if" } else { "elseif" },
                q(node, "id"),
                s(node, "id")
            ));
        }
        lines.extend([
            "\telse error(\"Host 返回了未知战斗续接节点: \" .. tostring(mod_resume_target)) end"
                .into(),
            "end".into(),
        ]);
    }
    lines.push(format!("return node_{}()", s(story, "start")));
    Ok(lines.join("\n") + "\n")
}
