[workspace]
members = ["rust/lom-core", "rust/lomc", "rust/lom-editor"]
resolver = "2"

[workspace.package]
version = "1.2.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision", "preserve_order"] }
sha2 = "0.10"
regex = "1"
tempfile = "3"
zip = { version = "2", default-features = false, features = ["deflate"] }
lom-core = { path = "rust/lom-core" }
