use serde_json::Value;
use std::{fs, process::Command};
#[test]
fn preflight_errors_and_failed_assertions_have_nonzero_exit() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().join("project");
    let mut project = lom_core::project::Project::new();
    project.stories.get_mut("main").unwrap()["_editor"] = serde_json::json!({"tests":[{"name":"unreachable assertion","story":"main","assert":{"reaches_node":["nonexistent"]}}]});
    project.save_to(&root).unwrap();
    let test = cli(&["test", root.to_str().unwrap(), "--json"]);
    assert_eq!(
        test.status.code(),
        Some(1),
        "{}",
        String::from_utf8_lossy(&test.stdout)
    );
    let mut manifest = project.manifest.clone();
    manifest["entry"] = serde_json::json!("missing");
    fs::write(
        root.join("manifest.json"),
        serde_json::to_vec(&manifest).unwrap(),
    )
    .unwrap();
    let check = cli(&["preflight", root.to_str().unwrap(), "--json"]);
    assert_eq!(check.status.code(), Some(1));
}
fn cli(args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_lomc"))
        .args(args)
        .output()
        .unwrap()
}
#[test]
fn native_cli_new_check_compile_and_error_exit() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("main.json");
    let input = path.to_str().unwrap();
    assert!(cli(&["new-story", input, "--json"]).status.success());
    let check = cli(&["check", input, "--json"]);
    assert!(
        check.status.success(),
        "{}",
        String::from_utf8_lossy(&check.stdout)
    );
    let build = cli(&["compile", input, "--json"]);
    let body: Value = serde_json::from_slice(&build.stdout).unwrap();
    assert_eq!(body["output"], path.with_extension("lua").to_str().unwrap());
    assert!(fs::read_to_string(path.with_extension("lua"))
        .unwrap()
        .contains("Generated by lomc"));
    fs::write(
        &path,
        r#"{"id":"main","start":"x","nodes":[{"id":"x","type":"invented"}]}"#,
    )
    .unwrap();
    let bad = cli(&["check", input, "--json"]);
    assert_eq!(bad.status.code(), Some(1));
    assert_eq!(
        serde_json::from_slice::<Value>(&bad.stdout).unwrap()["ok"],
        false
    );
}
#[test]
fn legacy_new_story_title_and_output_options() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("named.json");
    let result = cli(&[
        "--json",
        "new-story",
        "chapter_2",
        "--title",
        "第二章",
        "-o",
        path.to_str().unwrap(),
    ]);
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stdout)
    );
    let story: Value = serde_json::from_slice(&fs::read(path).unwrap()).unwrap();
    assert_eq!(story["id"], "chapter_2");
    assert_eq!(story["title"], "第二章");
    assert_eq!(
        cli(&[
            "new-story",
            "bad id",
            "-o",
            dir.path().join("bad.json").to_str().unwrap(),
            "--json"
        ])
        .status
        .code(),
        Some(1)
    );
}
#[test]
fn native_cli_pack_and_inspect() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().join("project");
    let mut project = lom_core::project::Project::new();
    project.save_to(&root).unwrap();
    let output = dir.path().join("test.lommod");
    let pack = cli(&[
        "pack",
        root.to_str().unwrap(),
        "-o",
        output.to_str().unwrap(),
        "--json",
    ]);
    assert!(
        pack.status.success(),
        "{}",
        String::from_utf8_lossy(&pack.stdout)
    );
    let inspect = cli(&["inspect", output.to_str().unwrap(), "--json"]);
    assert!(inspect.status.success());
    let body: Value = serde_json::from_slice(&inspect.stdout).unwrap();
    assert_eq!(body["manifest"]["package_format"], 3);
    assert_eq!(body["content_hash"].as_str().unwrap().len(), 64);
}
