# -*- coding: utf-8 -*-
"""story.json -> 游戏原生 Lua 代码生成（契约 v3 §4）。

- 每个节点编译为 node_<id>() 函数；文件头前向声明
  `local node_n1, node_n2, ...`，然后 `node_nX = function() ... end`；
  流转用尾调用 `return node_<goto>()`；顶层 `return node_<start>()`。
- 脚本开头 emit `modflags = modflags or {}`（mod 内 flag 表）与
  `mod_set_mood(true/false)`（story 顶层 mood 声明，默认 false）。
- 各节点 emit 范式逐条对应契约 §4（官方脚本实证，raw_scripts/ 可参考）。
- choice/branch/dice/end/goto_scene 自带流转，不追加顺序/goto 行；
  其余节点末尾追加 return node_<goto 或顺序下一节点>()。
"""

from .dice_data import get_dice_meta
from .errors import LomcError

GENERATED_MARK = "-- Generated by lomc, do not edit"


def lua_str(s):
    """契约 §4 转义：\\ → \\\\，" → \\"，换行 → \\n，\\r → \\r。"""
    return (
        '"'
        + s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        + '"'
    )


def lua_num(n):
    """数值 -> Lua 字面量。整数值不带小数点（与官方脚本风格一致）。"""
    if isinstance(n, bool):
        raise LomcError("内部错误：布尔值不能作为数值 emit")
    if isinstance(n, int):
        return str(n)
    f = float(n)
    if f.is_integer() and abs(f) < 1e15:
        return str(int(f))
    return repr(f)


def _lua_value(v):
    """字符串/数值通用字面量（block.vars 等 value 可为两种类型）。"""
    return lua_str(v) if isinstance(v, str) else lua_num(v)


def _get(char_expr):
    return "characters.Get(%s)" % char_expr


def _portrait(character, portrait):
    return "characters.GetPortrait(%s, %s)" % (character, portrait)


def _say_key(node, ctx):
    """say/death 文本的已读系统 key：MOD_<modid>_<scriptid>_<nodeid>。

    modid 取 ctx["mod_id"]（打包时来自 manifest）；独立 build / 编辑器
    预览没有 mod id 时用 "MOD" 兜底。
    """
    mod_id = ctx.get("mod_id") or "MOD"
    return "MOD_%s_%s_%s" % (mod_id, ctx["script_id"], node["id"])


# ---------------------------------------------------------------------------
# 演出类
# ---------------------------------------------------------------------------


def _emit_music(node, ctx):
    op = node.get("op", "play")
    if op == "stop":
        return ["\tluamanager.StopMusic()"]
    if op == "fadeout":
        return ["\tluamanager.FadeOutMusic(%s)" % lua_num(node.get("seconds", 2))]
    return ["\tluamanager.PlayMusic(%s)" % lua_str(node["name"])]


def _emit_sound(node, ctx):
    kind = node.get("kind", "sound")
    op = node.get("op", "play")
    if op == "fadeout":  # 校验已保证 kind="env"
        return ["\tluamanager.FadeOutEnvSound(%s)" % lua_num(node.get("seconds", 1))]
    if kind == "env":
        return ["\tluamanager.PlayEnvSound(%s)" % lua_str(node["name"])]
    return ["\tluamanager.PlaySound(%s)" % lua_str(node["name"])]


def _emit_scene(node, ctx):
    view = node["view"]
    lines = ['\trunblock(flowcharts.view, "out")']
    if view != "out":  # view="out" 时只淡出；"black"/"white" 为纯色，照常 emit
        # 官方实证：非纯色 view 必须先 LoadView 预加载背景资产（StoryViewImage
        # 的 Addressables 缓存为空时 view 块只显示空 sprite=黑背景；995/1111
        # 个官方脚本在 view 前都带 runwait(flowcharts.LoadView(...))）。
        if view not in ("black", "white"):
            lines.append("\trunwait(flowcharts.LoadView(%s))" % lua_str(view))
        lines.append('\tgetvar(flowcharts.view, "ViewName").value = %s' % lua_str(view))
        lines.append('\trunblock(flowcharts.view, "view")')
    return lines


def _emit_show(node, ctx):
    c = lua_str(node["character"])
    portrait = lua_str(node.get("portrait", "normal"))
    facing = lua_str(node.get("facing", "right"))
    pos = lua_str(node["position"])
    fade = lua_num(node.get("fadeDuration", 0))
    move = lua_num(node.get("moveDuration", 0))
    lines = [
        "\trunwait(characters.LoadCharacterAsset(%s))" % c,
        # 表情差分：先加载该表情的立绘差分（官方 93% show/say 均如此；
        # 不加载则台上人物立绘永远停在默认表情，只有气泡变）
        "\tcharacters.LoadCharacterPortrait(%s, %s)" % (c, portrait),
        "\tstage.show{character=%s, portrait=%s, fromPosition=%s, toPosition=%s, "
        "facing=%s, fadeDuration=%s, moveDuration=%s, useDefaultSettings=false}"
        % (_get(c), _portrait(c, portrait), pos, pos, facing, fade, move),
        "\tcharacters.Focus(%s)" % c,
    ]
    # 心情气泡：story mood 关闭时隐藏官方圆形情绪面板（show 后常驻）
    if not ctx.get("mood", False):
        lines.append("\tmod_hide_mood()")
    return lines


def _emit_move(node, ctx):
    c = lua_str(node["character"])
    duration = node.get("duration", 1)
    return [
        "\tstage.show{character=%s, fromPosition=%s, toPosition=%s, "
        "moveDuration=%s, useDefaultSettings=false}"
        % (_get(c), lua_str(node["from"]), lua_str(node["to"]), lua_num(duration)),
        "\twait(%s)" % lua_num(duration),
    ]


def _emit_face(node, ctx):
    return [
        "\tstage.show{character=%s, facing=%s, useDefaultSettings=false}"
        % (_get(lua_str(node["character"])), lua_str(node["facing"]))
    ]


def _emit_hide(node, ctx):
    return [
        "\tstage.hide{character=%s, fadeDuration=%s, useDefaultSettings=false}"
        % (_get(lua_str(node["character"])), lua_num(node.get("fadeDuration", 0)))
    ]


def _emit_focus(node, ctx):
    return ["\tcharacters.Focus(%s)" % lua_str(node["character"])]


def _emit_offset(node, ctx):
    return [
        "\trunwait(characters.MoveOffsetCoroutine(%s, %s, %s, %s))"
        % (
            lua_str(node["character"]),
            lua_num(node["x"]),
            lua_num(node["y"]),
            lua_num(node["duration"]),
        )
    ]


def _emit_say(node, ctx):
    mode = node.get("mode", "character")
    # 已读系统：文本不再裸字面量，改发射 key 查表（官方已读变黄/可快进机制）；
    # 文本本体进包内 texts.json，由运行时插件注册进 LeanLocalization。
    say_call = "\tsay(luamanager.GetStoryText(%s))" % lua_str(_say_key(node, ctx))
    hide_mood = "\tmod_hide_mood()" if not ctx.get("mood", False) else None

    def _with_mood(seq):
        # 心情气泡：story mood 关闭时 say 前/后各隐藏一次（发言会触发情绪面板）
        out = []
        for item in seq:
            if item == say_call:
                if hide_mood:
                    out.append(hide_mood)
                out.append(item)
                if hide_mood:
                    out.append(hide_mood)
            else:
                out.append(item)
        return out

    if mode in ("narrative", "center"):
        # 旁白/居中旁白：忽略 character（契约 §4）。
        # 官方实证：任何 say 前都要设 sayoptions（ch1_1 的 center 旁白同样如此），
        # 否则等待输入/淡出行为取决于环境默认值。
        return _with_mood(
            [
                "\tsetsaydialog(saydialogs.%s)" % mode,
                "\tsayoptions.waitforinput = true",
                "\tsayoptions.fadewhendone  = true",
                "\tsetcharacter(narrative)",
                say_call,
            ]
        )

    c = lua_str(node["character"])
    portrait = lua_str(node.get("portrait", "normal"))
    lines = [
        "\tsetsaydialog(saydialogs.%s)" % mode,
        # 表情差分：先加载该表情的立绘差分（官方 93% say 块均如此；
        # 不加载则台上人物立绘不换，只有气泡变）
        "\tcharacters.LoadCharacterPortrait(%s, %s)" % (c, portrait),
        "\tsayoptions.waitforinput = true",
        "\tsayoptions.fadewhendone  = true",
        "\tstage.showPortrait(%s, %s)" % (_get(c), _portrait(c, portrait)),
        "\tsetcharacter(%s, %s)" % (_get(c), _portrait(c, portrait)),
    ]
    if mode == "think":
        # 内心独白：say 前开独白遮罩，say 后关闭（契约 §4）
        lines.append("\tos_mask.SetLastPosition()")
        lines.append("\tos_mask.Show(true)")
    lines.append("\tcharacters.Focus(%s)" % c)
    lines.append(say_call)
    if mode == "think":
        lines.append("\tos_mask.Show(false)")
    return _with_mood(lines)


def _emit_choice(node, ctx):
    # 局部变量名固定 option1/choice1：每个节点一个独立函数，不会冲突
    dialog = node.get("dialog", "Options")  # §3.3 皮肤
    lines = [
        "\tsetmenudialog(menudialogs.%s)" % dialog,
        "\tlocal option1 = {}",
    ]
    for i, opt in enumerate(node["options"], 1):
        lines.append("\toption1[%d] = %s" % (i, lua_str(opt["text"])))
    lines.append("\tlocal choice1 = choose(option1)")
    lines.append("\tmenudialogs.%s.SetActive(false)" % dialog)
    for i, opt in enumerate(node["options"], 1):
        kw = "if" if i == 1 else "elseif"
        lines.append("\t%s choice1 == %d then" % (kw, i))
        lines.append("\t\treturn node_%s()" % opt["goto"])
    lines.append("\tend")
    return lines


def _emit_shock(node, ctx):
    c = lua_str(node["character"])
    return [
        '\tgetvar(flowcharts.common, "ShockPosition").value = %s.State.holder.gameObject'
        % _get(c),
        '\tgetvar(flowcharts.common, "ShockDuration").value = %s'
        % lua_num(node.get("duration", 0.5)),
        '\trunblock(flowcharts.common, "shock")',
    ]


def _emit_mask(node, ctx):
    return ["\tos_mask.Show(%s)" % ("true" if node["show"] else "false")]


def _emit_intro(node, ctx):
    if node.get("intro_source", "official") == "custom":
        return [
            "\tmod_prepare_character_intro(%s, %s, %s, %s, %s, %s, %s)"
            % (
                lua_str(node.get("title", "")),
                lua_str(node.get("name", "")),
                lua_str(node.get("text", "")),
                lua_str(node.get("image", "")),
                lua_num(node.get("image_scale", 100)),
                lua_num(node.get("image_x", 0)),
                lua_num(node.get("image_y", 0)),
            ),
            '\trunwait(intropanel.Show("__lommod_custom_intro__"))',
        ]
    return ["\trunwait(intropanel.Show(%s))" % lua_str(node["character"])]


def _emit_effect(node, ctx):
    """屏幕特效。play=False 时发射停止调用（官方循环特效不会自动销毁）。

    SetupEffect 最后一个参数 play：1=播放（循环类不自动销毁，官方实证
    EventBubble_001 / Glow_001 均有成对的 play=0 停止调用）、0=停止。
    优先用 play 字段；旧数据无 play 时用 d 字段（向后兼容）。
    """
    if "play" in node:
        play = 1 if node["play"] else 0
    else:
        play = node.get("d", 1)
    return [
        "\teffects.SetupEffect(%s, %s, %s, %s, %s, %s, %s)"
        % (
            lua_str(node["name"]),
            lua_num(node.get("x", 0)),
            lua_num(node.get("y", 0)),
            lua_num(node.get("a", 1)),
            lua_num(node.get("b", 1)),
            lua_num(node.get("c", 1)),
            lua_num(play),
        )
    ]


def _emit_transition(node, ctx):
    fn = "TransitionIn" if node["phase"] == "in" else "TransitionOut"
    return ["\trunwait(transitionblack.%s(%s))" % (fn, lua_str(node.get("dir", "lr")))]


def _emit_camera(node, ctx):
    return [
        "\tmaincamera.ActiveVolume(%s, %d)"
        % (lua_str(node["name"]), 1 if node["active"] else 0)
    ]


def _emit_block(node, ctx):
    fc = "flowcharts.%s" % node["flowchart"]
    lines = []
    for var in node.get("vars", []):
        lines.append(
            "\tgetvar(%s, %s).value = %s"
            % (fc, lua_str(var["name"]), _lua_value(var["value"]))
        )
    lines.append("\trunblock(%s, %s)" % (fc, lua_str(node["name"])))
    return lines


# cg 各 action/kind 组合的官方调用（raw_scripts 实证）
_CG_SHOW = {
    "picture": ("runwait(mainui.ShowPicture(%s))", ("key",)),
    "item": ("runwait(mainui.ShowItemPicture(%s))", ("key",)),
    "big": ("runwait(mainui.ShowBigPicture(%s))", ("key",)),
    "map": ("runwait(mainui.ShowMap(%s, %s))", ("key", "key2")),
    "family": (
        "runwait(mainui.ShowFamilyTree(%s, %s, %s, %s))",
        ("key", "key2", "n1", "n2"),
    ),
    "title": ("mainui.DisplayTitle(%s)", ("key",)),  # 官方 DisplayTitle 无 runwait
}
_CG_HIDE = {
    "picture": "runwait(mainui.HidePicture())",
    "item": "runwait(mainui.HideItemPicture())",
    "big": "runwait(mainui.HideBigPicture())",
    "map": "runwait(mainui.HideMap())",
    "family": "runwait(mainui.HideFamilyTree())",
    # title 无官方 hide API，已在校验阶段拦截
}


def _emit_cg(node, ctx):
    action, kind = node["action"], node["kind"]
    if action == "hide":
        return ["\t" + _CG_HIDE[kind]]
    fmt, arg_names = _CG_SHOW[kind]
    args = [_lua_value(node[k]) for k in arg_names]
    return ["\t" + fmt % tuple(args)]


def _emit_dim(node, ctx):
    """人物压暗：stage.SetDimmed(character, dimmedState)（官方 API，实参顺序
    character 在前、bool 在后）。dimmed=true 时官方实现还会隐藏该角色心情气泡。
    """
    return [
        "\tstage.SetDimmed(%s, %s)"
        % (_get(lua_str(node["character"])), "true" if node["dimmed"] else "false")
    ]


def _emit_message(node, ctx):
    """系统提示：mainui.DisplayMessageText(text) 显示原文（DisplayMessage 走
    key 解析，用 Text 版避免自定文本被当本地化 key）。
    """
    return ["\tmainui.DisplayMessageText(%s)" % lua_str(node["text"])]


def _emit_rotate(node, ctx):
    """人物旋转：characters.Rotate(key, angle, duration)——注意官方参数序
    angle 在前、duration 在后（StoryCharacterController.Rotate(duration, angle)
    内部再交换，raw_scripts 调用点实证）。
    """
    return [
        "\tcharacters.Rotate(%s, %s, %s)"
        % (
            lua_str(node["character"]),
            lua_num(node["angle"]),
            lua_num(node["duration"]),
        )
    ]


def _emit_dayenv(node, ctx):
    """日夜环境：luamanager.SetGameDayEnvironment(day_type)。DayEnvironmentType
    枚举（raw_scripts 调用点实证）：1=白天，2=晚上。
    """
    return ["\tluamanager.SetGameDayEnvironment(%s)" % lua_num(node["day_type"])]


# ---------------------------------------------------------------------------
# 数值/状态类
# ---------------------------------------------------------------------------


def _emit_stat(node, ctx):
    key = lua_str(node["key"])
    lines = [
        "\tstatmodifymanager.Player(%s, %s, %s, %s)"
        % (
            key,
            lua_num(node["delta"]),
            lua_str(node.get("mode", "")),
            lua_num(node.get("display", 1)),
        )
    ]
    if node.get("waitDisplay", True):
        lines.append("\twait(statmodifymanager.GetDisplayTime(%s))" % key)
    return lines


def _emit_stat_set(node, ctx):
    fn = "UpdateSetPlayerStat" if node.get("update", False) else "SetPlayer"
    return [
        "\tstatmodifymanager.%s(%s, %s)"
        % (fn, lua_str(node["key"]), lua_num(node["value"]))
    ]


def _emit_affinity(node, ctx):
    return [
        "\tstatmodifymanager.Character(%s, %s, 1)"
        % (lua_str(node["character"]), lua_num(node["delta"]))
    ]


def _emit_talent(node, ctx):
    return [
        "\tstatmodifymanager.AddTalent(%s, %s)"
        % (lua_str(node["talent"]), lua_num(node["level"]))
    ]


_ITEM_API = {"book": "Book", "misc": "Misc", "special": "Special"}


def _emit_item(node, ctx):
    api = _ITEM_API[node["kind"]]
    if node.get("remove", False):  # 校验已保证 kind != special
        return ["\tstatmodifymanager.Remove%s(%s)" % (api, lua_str(node["item"]))]
    return [
        "\tstatmodifymanager.Add%s(%s, %s)"
        % (api, lua_str(node["item"]), lua_num(node.get("count", 1)))
    ]


def _emit_flag(node, ctx):
    # 契约 §4：写游戏经历 + 设置 mod 内状态（供 branch source="mod" 判断）
    f = lua_str(node["flag"])
    return [
        "\tstatmodifymanager.AddStory(%s)" % f,
        "\tmodflags[%s] = true" % f,
    ]


def _emit_game_flag(node, ctx):
    fn = "AddFlag" if node.get("op", "set") == "add" else "SetFlag"
    return [
        "\tstatmodifymanager.%s(%s, %s)"
        % (fn, lua_str(node["flag"]), lua_num(node["value"]))
    ]


_ENEMY_API = {
    "team": "ModifyEnemyTeam",
    "level": "ModifyEnemyLevel",
    "people": "ModifyEnemyPeople",
}


def _emit_enemy(node, ctx):
    op = node["op"]
    if op == "id":
        return ["\tstatmodifymanager.ModifyEnemyId(%s)" % lua_str(node["enemy"])]
    return [
        "\tstatmodifymanager.%s(%s, %s, %s)"
        % (
            _ENEMY_API[op],
            lua_str(node["enemy"]),
            lua_num(node["value"]),
            lua_num(node.get("display", 1)),
        )
    ]


def _emit_battle_skill(node, ctx):
    op = node["op"]
    if op == "reset":
        return ["\tluamanager.ResetBattleSkill()"]
    if op == "active":
        return [
            "\tluamanager.SetBattleSkillActive(%s, %s)"
            % (lua_str(node["key"]), lua_num(node.get("active", 1)))
        ]
    return [
        "\tluamanager.SetPlayerBattleSkill(%s, %s)"
        % (lua_str(node["key"]), lua_num(node.get("index", 2)))
    ]


def _emit_mission(node, ctx):
    return [
        "\tstatmodifymanager.Mission(%s, %s)"
        % (lua_str(node["name"]), lua_str(node["key"]))
    ]


def _emit_time(node, ctx):
    op = node["op"]
    if op == "round":
        return ["\tluamanager.NextRound()"]
    if op == "month":
        return ["\tluamanager.NextMonth()"]
    if op == "mission":
        return [
            "\tluamanager.SetMissionTime(%s, %s, %s, %s)"
            % (
                lua_str(node["name"]),
                lua_num(node["year"]),
                lua_num(node["month"]),
                lua_num(node["stage"]),
            )
        ]
    return [
        "\tluamanager.SetGameTime(%s, %s, %s)"
        % (lua_num(node["year"]), lua_num(node["month"]), lua_num(node["stage"]))
    ]


def _emit_autosave(node, ctx):
    kind = node.get("kind", "story")
    lines = []
    if kind == "free":
        lines.append("\tluamanager.AutoFreeSave()")
    elif kind == "prologue":
        # 契约 §3.1 写作 PrologueSave(mode) 但未给 mode 字段；官方两处分别
        # 传 1/0（序幕首尾），语义不明，固定取 0（见契约歧义说明）
        lines.append("\tluamanager.PrologueSave(0)")
    else:
        lines.append("\tluamanager.AutoSave()")
    if "save_button" in node:
        lines.append("\tluamanager.ToggleSaveButton(%d)" % node["save_button"])
    return lines


# ---------------------------------------------------------------------------
# 流程类
# ---------------------------------------------------------------------------


def _emit_branch(node, ctx):
    """分支（契约 §4，五种 source；未命中必须有 else 兜底）。

    ctx["next_id"] 为顺序下一节点 id，作为 else 的默认落点；
    校验已保证需要兜底时 next_id 一定存在。
    """
    source = node.get("source", "mod")
    flag = lua_str(node["flag"]) if "flag" in node else None
    next_id = ctx.get("next_id")
    if source == "mod":
        # 按 modflags[flag] 是否已设置二分：value 1=已设置(then)，2=未设置(else)；
        # 缺某一路时该路落顺序下一节点。
        cases = {c["value"]: c["goto"] for c in node["cases"]}
        then_goto = cases.get(1, next_id)
        else_goto = cases.get(2, next_id)
        return [
            "\tif modflags[%s] then" % flag,
            "\t\treturn node_%s()" % then_goto,
            "\telse",
            "\t\treturn node_%s()" % else_goto,
            "\tend",
        ]
    if source == "condition":
        # 官方条件检查点：checkpointmanager.Condition(flag) 返回 bool；
        # value 1=真(then)，2=假(else)，缺某一路时该路落顺序下一节点。
        cases = {c["value"]: c["goto"] for c in node["cases"]}
        then_goto = cases.get(1, next_id)
        else_goto = cases.get(2, next_id)
        return [
            "\tif checkpointmanager.Condition(%s) then" % flag,
            "\t\treturn node_%s()" % then_goto,
            "\telse",
            "\t\treturn node_%s()" % else_goto,
            "\tend",
        ]
    if source == "stat":
        # 主角属性数值分支：GetStatData(stat, 1)（sign=1 取正值）；
        # 按 case 的 op/value 逐项比较，未命中 else 兜底。
        lines = [
            "\tlocal branch1 = luamanager.GetStatData(%s, 1)" % lua_str(node["stat"])
        ]
        for i, case in enumerate(node["cases"]):
            kw = "if" if i == 0 else "elseif"
            lines.append(
                "\t%s branch1 %s %s then"
                % (kw, case.get("op", ">="), lua_num(case["value"]))
            )
            lines.append("\t\treturn node_%s()" % case["goto"])
        lines.append("\telse")
        lines.append("\t\treturn node_%s()" % next_id)
        lines.append("\tend")
        return lines
    if source == "flag_value":
        # 官方任务旗标数值分支：tonumber(GetFlagData(flag)) + 同 stat 的比较
        lines = ["\tlocal branch1 = tonumber(luamanager.GetFlagData(%s))" % flag]
        for i, case in enumerate(node["cases"]):
            kw = "if" if i == 0 else "elseif"
            lines.append(
                "\t%s branch1 %s %s then"
                % (kw, case.get("op", ">="), lua_num(case["value"]))
            )
            lines.append("\t\treturn node_%s()" % case["goto"])
        lines.append("\telse")
        lines.append("\t\treturn node_%s()" % next_id)
        lines.append("\tend")
        return lines
    # source="game"：读官方检查点，Switch 找不到时返回 0，else 兜底落顺序下一节点
    lines = ["\tlocal branch1 = checkpointmanager.Switch(%s)" % flag]
    for i, case in enumerate(node["cases"]):
        kw = "if" if i == 0 else "elseif"
        lines.append("\t%s branch1 == %s then" % (kw, lua_num(case["value"])))
        lines.append("\t\treturn node_%s()" % case["goto"])
    lines.append("\telse")
    lines.append("\t\treturn node_%s()" % next_id)
    lines.append("\tend")
    return lines


def _band_rank(bands):
    """结果带质量排名：返回每个带的名次 1..N（最差→最好）。

    检查点的结果带顺序不保证是差→好（官方有 34 个倒序检查点，如
    ['>80', '>40', '<=40']），因此按条件文本的数值推断质量：
    数值越大越好；同数值时 '>'/'>=/'=' 优于 '<'/'<='（更窄的顶带）。
    解析不了条件的带按展示顺序兜底。
    """
    import re as _re

    parsed = []
    for b in bands:
        m = _re.search(r"(<=|>=|<|>|=)\s*(\d+)", str(b.get("cond", "")))
        if m:
            op, num = m.group(1), int(m.group(2))
            parsed.append((num, op in (">", ">=", "=")))
        else:
            parsed.append(None)
    if not any(p is not None for p in parsed):
        return list(range(1, len(bands) + 1))
    order = sorted(
        range(len(bands)),
        key=lambda i: (
            parsed[i][0] if parsed[i] is not None else -1,
            parsed[i][1] if parsed[i] is not None else False,
        ),
    )
    ranks = [0] * len(bands)
    for rank, i in enumerate(order, 1):
        ranks[i] = rank
    return ranks


def _emit_dice(node, ctx):
    """骰子检定：按检查点官方元数据发射（骰子范围、结果带条数与文本）。

    官方实证（travel_result_601_101 / ch6_8_2_break_start_01 等）：骰子菜单
    按结果带索引选项按钮（UpdateSelection 用 ResultSelection-1 做下标），
    选项条数必须 >= 结果带数，否则越界 NRE、菜单卡死（继续按钮永不出现）。
    选项按官方提取顺序发射（菜单高亮按此索引），分支按带的质量名次映射：
    最差带→goto_失败；3 带及以上时最优带→goto_大成功、中间带→goto_成功；
    2 带时最优带→goto_成功（无独立大成功档）。

    options[0]["band_texts"]（可选，列表）：逐带覆写选项文本（作者自定义
    文本字面量，游戏 GetStoryText 查不到 key 时原样显示，无需进 texts.json）；
    缺省时用官方结果带文本。条件部分永远用官方元数据。
    """
    check = node["check"]
    meta = get_dice_meta(check) or {}
    bands = meta.get("bands") or [
        {"text": str(node["options"][0].get("text", "")), "cond": ""}
    ]
    dice_max = meta.get("max", 99)
    opt = node["options"][0]
    band_texts = opt.get("band_texts")
    lines = [
        "	setmenudialog(menudialogs.Dice)",
        "	local dice_rand1 = math.random(%d)" % dice_max,
        "	dicemenudialog.SetRandom(%d, dice_rand1)" % dice_max,
        "	local dice_result1 = checkpointmanager.Dice(%s, dice_rand1)"
        % lua_str(check),
        "	local dice_opts1 = {}",
    ]
    for i, band in enumerate(bands, 1):
        # 文本会被游戏当本地化 key 解析（GetStoryText 查不到时原样返回）；
        # ASCII | 换成全角｜防分隔符冲突（条件部分紧随其后）
        if isinstance(band_texts, list) and len(band_texts) == len(bands):
            text = str(band_texts[i - 1]).replace("|", "｜")
        else:
            text = str(band.get("text", "")).replace("|", "｜")
        entry = "%s|%s" % (text, band.get("cond", ""))
        lines.append("	dice_opts1[%d] = %s" % (i, lua_str(entry)))
    lines += [
        "	dicemenudialog.Setup(dice_result1.ResultCount, dice_result1.Result, "
        "dice_result1.Header, dice_result1.Additions)",
        "	runwait(dicemenudialog.ExecuteRoll(dice_opts1, 1, %s))" % lua_str(check),
        "	local dice_sel1 = dicemenudialog.ResultSelection",
    ]
    n = len(bands)
    ranks = _band_rank(bands)

    def goto_for_rank(r):
        if r == 1:
            return opt["goto_失败"]
        if r == n and n >= 3:
            return opt["goto_大成功"]
        return opt["goto_成功"]

    if n == 2:
        lines += [
            "	if dice_sel1 == 1 then",
            "		return node_%s()" % goto_for_rank(ranks[0]),
            "	else",
            "		return node_%s()" % goto_for_rank(ranks[1]),
            "	end",
        ]
    else:
        lines.append("	if dice_sel1 == 1 then")
        lines.append("		return node_%s()" % goto_for_rank(ranks[0]))
        for i in range(1, n - 1):
            lines.append("	elseif dice_sel1 == %d then" % (i + 1))
            lines.append("		return node_%s()" % goto_for_rank(ranks[i]))
        lines.append("	else")
        lines.append("		return node_%s()" % goto_for_rank(ranks[n - 1]))
        lines.append("	end")
    return lines


def _emit_goto_scene(node, ctx):
    lines = []
    # End 不是跳进简化 End 场景：原版真正的“汗青书结局卡”流程是
    # endgamepanel.Open(key) -> 玩家确认 -> 黑幕 -> Title。运行时 patch 在官方
    # EndGamePanel 第一次 yield 前写入 mod 标题/正文/插图，因此完整复用官方版式、
    # 渐显和确认输入。原版所有 EndGamePanel 结局在玩家确认后都回 Title；旧格式的
    # next 字段继续允许读取，但不再制造一个游戏本身不存在的自定义返回去向。
    if node["scene"] == "End" and "image" in node:
        lines.append(
            "\tmod_set_ending_text(%s, %s, %s)"
            % (
                lua_str(node.get("title", "")),
                lua_str(node.get("desc", "")),
                lua_str(node["image"]),
            )
        )
    elif node["scene"] == "End" and ("title" in node or "desc" in node):
        lines.append(
            "\tmod_set_ending_text(%s, %s)"
            % (lua_str(node.get("title", "")), lua_str(node.get("desc", "")))
        )
    elif node["scene"] == "GameOver" and ("title" in node or "desc" in node):
        # GameOver 使用死亡覆盖通道，避免把 EndingRequested/结局图片状态带进
        # 死亡场景；显示布局仍由同一个官方 GameOverController patch 完成。
        lines.append(
            "\tmod_set_death_text(%s, %s)"
            % (lua_str(node.get("title", "")), lua_str(node.get("desc", "")))
        )
    if node["scene"] == "End":
        has_mod_content = any(
            isinstance(node.get(name), str) and node[name].strip()
            for name in ("title", "desc", "image")
        )
        panel_key = "__MORTAL_MOD_END__" if has_mod_content else node.get("key", "")
        lines += [
            "\tluamanager.SetEnableActions(0)",
            "\trunwait(endgamepanel.Open(%s))" % lua_str(panel_key),
            "\tluamanager.SetEnableActions(1)",
            '\trunwait(transitionblack.TransitionIn("lr"))',
            '\tluamanager.ChangeScene("Title", "", "")',
        ]
        return lines
    next_scene = "Title" if node["scene"] == "GameOver" else node.get("next", "Story")
    lines.append(
        "\tluamanager.ChangeScene(%s, %s, %s)"
        % (
            lua_str(node["scene"]),
            lua_str(node.get("key", "")),
            lua_str(next_scene),
        )
    )
    return lines


def _emit_panel(node, ctx):
    p = node["panel"]
    if p == "martial":
        return ["\trunwait(martialpanel.Open(%s))" % lua_num(node.get("mode", 0))]
    if p == "weapon":
        return ["\trunwait(weaponupgradepanel.Open())"]
    if p == "poison":
        return ["\trunwait(poisonupgradepanel.Open())"]
    if p == "cg":
        return ["\trunwait(cgpanel.Open(%s))" % lua_str(node["key"])]
    if p == "cgvideo":
        return ["\trunwait(cgvideopanel.Open(%s, 0))" % lua_str(node["key"])]
    if p == "shop":
        return ["\trunwait(shoppanel.Open(%s))" % lua_num(node.get("discount", 0))]
    if p == "newshop":  # 契约 §3.1：除 newshop 外均 runwait
        return ["\tshoppanel.NewShop()"]
    if p == "credit":
        return ["\trunwait(creditpanel.Open())"]
    # endgame
    return ["\trunwait(endgamepanel.Open(%s))" % lua_str(node["key"])]


def _emit_wait(node, ctx):
    return ["\twait(%s)" % lua_num(node["seconds"])]


def _emit_end(node, ctx):
    next_script = node.get("next_script")
    if next_script is None:
        # 无 next_script：官方标准收尾，返回自由模式（契约 §3.1）。
        # 注意不能 emit luamanager.Init()：无后续脚本时 Init 会重跑当前
        # 脚本，造成死循环。
        return ['\tluamanager.ChangeScene("Free", "", "")']
    # 有 next_script：链到同包内另一脚本。运行时注册名带 MOD_<modid>_
    # 前缀（契约 §3.1/§6）；裸 build 不知 mod id 时退化为原始脚本 id。
    target = (
        "MOD_%s_%s" % (ctx["mod_id"], next_script) if ctx.get("mod_id") else next_script
    )
    return [
        "\tluamanager.SetNextScript(%s)" % lua_str(target),
        "\tluamanager.Init()",
    ]


def _emit_death(node, ctx):
    """死亡文本节点：黑屏过渡 → mod_set_death_text(title, text) → 官方 GameOver 死亡画面。

    自定死亡文本两段式：短标题（缺省「勝敗乃兵家常事」）+ 多行描述，均 lua_str
    字面量（不进 texts.json / 已读系统）；运行时插件 patch GameOverController
    把两段文本显示在官方死亡画面中央（标题栏 + 黑底红字 + 返回按钮，契约 §6）。
    death_id 必须是 ≥900000 的 mod 专属 id：官方 GameOver 场景用 id 查
    LibrarySystem 并解锁/记录官方结局，mod 专属 id 查不到 → 无副作用，但
    死亡画面本身照常显示（校验见 validate.py）。
    """
    title = node.get("title") or "勝敗乃兵家常事"
    return [
        '\trunblock(flowcharts.view, "out")',
        '\tgetvar(flowcharts.view, "ViewName").value = "black"',
        '\trunblock(flowcharts.view, "view")',
        "\tmod_set_death_text(%s, %s)" % (lua_str(title), lua_str(node["text"])),
        "\tluamanager.ChangeScene(%s, %s, %s)"
        % (
            lua_str("GameOver"),
            lua_str(node["death_id"]),
            # 原版 GameOverController 的按钮固定为读档 / Title，不读取
            # CurrentNextScene；统一写 Title，避免生成看似可配置但实际无效的数据。
            lua_str("Title"),
        ),
    ]


def _emit_raw(node, ctx):
    # 原生 Lua 逃逸口：原样插入（契约 §4）。
    # 不加缩进——code 里可能含 [[...]] 长字符串，改动空白会改变内容。
    return node["code"].splitlines()


_EMITTERS = {
    "music": _emit_music,
    "sound": _emit_sound,
    "scene": _emit_scene,
    "show": _emit_show,
    "move": _emit_move,
    "face": _emit_face,
    "hide": _emit_hide,
    "focus": _emit_focus,
    "offset": _emit_offset,
    "say": _emit_say,
    "choice": _emit_choice,
    "shock": _emit_shock,
    "mask": _emit_mask,
    "intro": _emit_intro,
    "effect": _emit_effect,
    "transition": _emit_transition,
    "camera": _emit_camera,
    "block": _emit_block,
    "cg": _emit_cg,
    "dim": _emit_dim,
    "message": _emit_message,
    "rotate": _emit_rotate,
    "dayenv": _emit_dayenv,
    "stat": _emit_stat,
    "stat_set": _emit_stat_set,
    "affinity": _emit_affinity,
    "talent": _emit_talent,
    "item": _emit_item,
    "flag": _emit_flag,
    "game_flag": _emit_game_flag,
    "enemy": _emit_enemy,
    "battle_skill": _emit_battle_skill,
    "mission": _emit_mission,
    "time": _emit_time,
    "autosave": _emit_autosave,
    "branch": _emit_branch,
    "dice": _emit_dice,
    "goto_scene": _emit_goto_scene,
    "panel": _emit_panel,
    "wait": _emit_wait,
    "end": _emit_end,
    "death": _emit_death,
    "raw": _emit_raw,
}

# 自带流转（分支/跳转/场景切换），story_to_lua 不再追加 return node_<goto>() 行
_NO_FLOW_TYPES = ("end", "choice", "branch", "dice", "goto_scene", "death")


def story_to_lua(story, mod_info=None, source=None):
    """把已校验的 story dict 编译为 Lua 源码字符串。

    mod_info：可选的 manifest dict（pack 时传入），用于文件头注释与
    end 节点 SetNextScript 的 MOD_<modid>_ 前缀。
    source：可选的来源描述（通常是 story/<id>.json），写进文件头注释。
    """
    ctx = {
        "mod_id": mod_info.get("id") if mod_info else None,
        "script_id": story["id"],
        "mood": bool(story.get("mood", False)),
    }
    nodes = story["nodes"]

    lines = [GENERATED_MARK]
    src = source or ("story/%s.json" % story["id"])
    title = story.get("title", "")
    lines.append("-- Source: %s (id=%s, title=%s)" % (src, story["id"], title))
    if mod_info:
        lines.append(
            "-- Mod: %s (%s) v%s by %s"
            % (
                mod_info.get("id", ""),
                mod_info.get("name", ""),
                mod_info.get("version", ""),
                mod_info.get("author", ""),
            )
        )
    lines.append("")

    # 契约 §4：每个脚本开头初始化 mod 内 flag 表（全局表，链式脚本间共享）
    lines.append("-- mod 内剧情 flag 表（不存档，重进游戏清零）")
    lines.append("modflags = modflags or {}")
    # 契约 §4：mood 声明——每个脚本开头声明本脚本心情气泡开关（story 顶层
    # mood 字段，默认 false）；运行时插件注册 mod_set_mood 全局并硬控 ShowMood，
    # 与 mod_hide_mood 双保险防官方情绪面板干扰剧情演出。
    lines.append("mod_set_mood(%s)" % ("true" if ctx["mood"] else "false"))
    lines.append("")

    # 前向声明全部节点函数：Lua 的 local function 无法引用后定义的 local，
    # 而汇合点 / 分支回环要求任意方向的跳转。
    lines.append("-- 节点函数前向声明（支持任意 goto / 分支回环）")
    lines.append("local " + ", ".join("node_%s" % n["id"] for n in nodes))
    lines.append("")

    for i, node in enumerate(nodes):
        lines.append("-- [%s] %s" % (node["id"], node["type"]))
        lines.append("node_%s = function()" % node["id"])
        emitter = _EMITTERS.get(node["type"])
        if emitter is None:
            raise LomcError(
                '内部错误：节点 "%s" 类型 "%s" 未校验通过' % (node["id"], node["type"])
            )
        # branch 的 else 兜底需要顺序下一节点 id（校验已保证需要时存在）
        ctx["next_id"] = nodes[i + 1]["id"] if i + 1 < len(nodes) else None
        lines.extend(emitter(node, ctx))
        if node["type"] not in _NO_FLOW_TYPES:
            # 显式 goto 覆盖顺序流（契约 §3）；校验已保证目标存在
            goto = node.get("goto")
            if goto is None:
                goto = nodes[i + 1]["id"]
            lines.append("\treturn node_%s()" % goto)
        lines.append("end")
        lines.append("")

    lines.append("return node_%s()" % story["start"])
    return "\n".join(lines) + "\n"
