# -*- coding: utf-8 -*-
"""story.json -> 游戏原生 Lua 代码生成（契约 v3 §4）。

- 每个节点编译为 node_<id>() 函数；文件头前向声明
  `local node_n1, node_n2, ...`，然后 `node_nX = function() ... end`；
  流转用尾调用 `return node_<goto>()`；顶层 `return node_<start>()`。
- 脚本开头 emit `modflags = modflags or {}`（mod 内 flag 表）。
- 各节点 emit 范式逐条对应契约 §4（官方脚本实证，raw_scripts/ 可参考）。
- choice/branch/dice/end/goto_scene 自带流转，不追加顺序/goto 行；
  其余节点末尾追加 return node_<goto 或顺序下一节点>()。
"""

from .errors import LomcError

GENERATED_MARK = "-- Generated by lomc, do not edit"


def lua_str(s):
    """契约 §4 转义：\\ → \\\\，" → \\"，换行 → \\n，\\r → \\r。"""
    return (
        '"'
        + s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        + '"'
    )


def lua_num(n):
    """数值 -> Lua 字面量。整数值不带小数点（与官方脚本风格一致）。"""
    if isinstance(n, bool):
        raise LomcError("内部错误：布尔值不能作为数值 emit")
    if isinstance(n, int):
        return str(n)
    f = float(n)
    if f.is_integer() and abs(f) < 1e15:
        return str(int(f))
    return repr(f)


def _lua_value(v):
    """字符串/数值通用字面量（block.vars 等 value 可为两种类型）。"""
    return lua_str(v) if isinstance(v, str) else lua_num(v)


def _get(char_expr):
    return "characters.Get(%s)" % char_expr


def _portrait(character, portrait):
    return "characters.GetPortrait(%s, %s)" % (character, portrait)


# ---------------------------------------------------------------------------
# 演出类
# ---------------------------------------------------------------------------


def _emit_music(node, ctx):
    op = node.get("op", "play")
    if op == "stop":
        return ["\tluamanager.StopMusic()"]
    if op == "fadeout":
        return ["\tluamanager.FadeOutMusic(%s)" % lua_num(node.get("seconds", 2))]
    return ["\tluamanager.PlayMusic(%s)" % lua_str(node["name"])]


def _emit_sound(node, ctx):
    kind = node.get("kind", "sound")
    op = node.get("op", "play")
    if op == "fadeout":  # 校验已保证 kind="env"
        return ["\tluamanager.FadeOutEnvSound(%s)" % lua_num(node.get("seconds", 1))]
    if kind == "env":
        return ["\tluamanager.PlayEnvSound(%s)" % lua_str(node["name"])]
    return ["\tluamanager.PlaySound(%s)" % lua_str(node["name"])]


def _emit_scene(node, ctx):
    view = node["view"]
    lines = ['\trunblock(flowcharts.view, "out")']
    if view != "out":  # view="out" 时只淡出；"black"/"white" 为纯色，照常 emit
        lines.append('\tgetvar(flowcharts.view, "ViewName").value = %s' % lua_str(view))
        lines.append('\trunblock(flowcharts.view, "view")')
    return lines


def _emit_show(node, ctx):
    c = lua_str(node["character"])
    portrait = lua_str(node.get("portrait", "normal"))
    facing = lua_str(node.get("facing", "right"))
    pos = lua_str(node["position"])
    fade = lua_num(node.get("fadeDuration", 0))
    move = lua_num(node.get("moveDuration", 0))
    return [
        "\trunwait(characters.LoadCharacterAsset(%s))" % c,
        "\tstage.show{character=%s, portrait=%s, fromPosition=%s, toPosition=%s, "
        "facing=%s, fadeDuration=%s, moveDuration=%s, useDefaultSettings=false}"
        % (_get(c), _portrait(c, portrait), pos, pos, facing, fade, move),
        "\tcharacters.Focus(%s)" % c,
    ]


def _emit_move(node, ctx):
    c = lua_str(node["character"])
    duration = node.get("duration", 1)
    return [
        "\tstage.show{character=%s, fromPosition=%s, toPosition=%s, "
        "moveDuration=%s, useDefaultSettings=false}"
        % (_get(c), lua_str(node["from"]), lua_str(node["to"]), lua_num(duration)),
        "\twait(%s)" % lua_num(duration),
    ]


def _emit_face(node, ctx):
    return [
        "\tstage.show{character=%s, facing=%s, useDefaultSettings=false}"
        % (_get(lua_str(node["character"])), lua_str(node["facing"]))
    ]


def _emit_hide(node, ctx):
    return [
        "\tstage.hide{character=%s, fadeDuration=%s, useDefaultSettings=false}"
        % (_get(lua_str(node["character"])), lua_num(node.get("fadeDuration", 0)))
    ]


def _emit_focus(node, ctx):
    return ["\tcharacters.Focus(%s)" % lua_str(node["character"])]


def _emit_offset(node, ctx):
    return [
        "\trunwait(characters.MoveOffsetCoroutine(%s, %s, %s, %s))"
        % (
            lua_str(node["character"]),
            lua_num(node["x"]),
            lua_num(node["y"]),
            lua_num(node["duration"]),
        )
    ]


def _emit_say(node, ctx):
    mode = node.get("mode", "character")
    text = lua_str(node["text"])
    if mode in ("narrative", "center"):
        # 旁白/居中旁白：忽略 character（契约 §4）。
        # 官方实证：任何 say 前都要设 sayoptions（ch1_1 的 center 旁白同样如此），
        # 否则等待输入/淡出行为取决于环境默认值。
        return [
            "\tsetsaydialog(saydialogs.%s)" % mode,
            "\tsayoptions.waitforinput = true",
            "\tsayoptions.fadewhendone  = true",
            "\tsetcharacter(narrative)",
            "\tsay(%s)" % text,
        ]

    c = lua_str(node["character"])
    portrait = lua_str(node.get("portrait", "normal"))
    lines = [
        "\tsetsaydialog(saydialogs.%s)" % mode,
        "\tsayoptions.waitforinput = true",
        "\tsayoptions.fadewhendone  = true",
        "\tstage.showPortrait(%s, %s)" % (_get(c), _portrait(c, portrait)),
        "\tsetcharacter(%s, %s)" % (_get(c), _portrait(c, portrait)),
    ]
    if mode == "think":
        # 内心独白：say 前开独白遮罩，say 后关闭（契约 §4）
        lines.append("\tos_mask.SetLastPosition()")
        lines.append("\tos_mask.Show(true)")
    lines.append("\tcharacters.Focus(%s)" % c)
    lines.append("\tsay(%s)" % text)
    if mode == "think":
        lines.append("\tos_mask.Show(false)")
    return lines


def _emit_choice(node, ctx):
    # 局部变量名固定 option1/choice1：每个节点一个独立函数，不会冲突
    dialog = node.get("dialog", "Options")  # §3.3 皮肤
    lines = [
        "\tsetmenudialog(menudialogs.%s)" % dialog,
        "\tlocal option1 = {}",
    ]
    for i, opt in enumerate(node["options"], 1):
        lines.append("\toption1[%d] = %s" % (i, lua_str(opt["text"])))
    lines.append("\tlocal choice1 = choose(option1)")
    lines.append("\tmenudialogs.%s.SetActive(false)" % dialog)
    for i, opt in enumerate(node["options"], 1):
        kw = "if" if i == 1 else "elseif"
        lines.append("\t%s choice1 == %d then" % (kw, i))
        lines.append("\t\treturn node_%s()" % opt["goto"])
    lines.append("\tend")
    return lines


def _emit_shock(node, ctx):
    c = lua_str(node["character"])
    return [
        '\tgetvar(flowcharts.common, "ShockPosition").value = %s.State.holder.gameObject' % _get(c),
        '\tgetvar(flowcharts.common, "ShockDuration").value = %s' % lua_num(node.get("duration", 0.5)),
        '\trunblock(flowcharts.common, "shock")',
    ]


def _emit_mask(node, ctx):
    return ["\tos_mask.Show(%s)" % ("true" if node["show"] else "false")]


def _emit_intro(node, ctx):
    return ["\trunwait(intropanel.Show(%s))" % lua_str(node["character"])]


def _emit_effect(node, ctx):
    return [
        "\teffects.SetupEffect(%s, %s, %s, %s, %s, %s, %s)"
        % (
            lua_str(node["name"]),
            lua_num(node.get("x", 0)),
            lua_num(node.get("y", 0)),
            lua_num(node.get("a", 1)),
            lua_num(node.get("b", 1)),
            lua_num(node.get("c", 1)),
            lua_num(node.get("d", 1)),
        )
    ]


def _emit_transition(node, ctx):
    fn = "TransitionIn" if node["phase"] == "in" else "TransitionOut"
    return ["\trunwait(transitionblack.%s(%s))" % (fn, lua_str(node.get("dir", "lr")))]


def _emit_camera(node, ctx):
    return [
        "\tmaincamera.ActiveVolume(%s, %d)"
        % (lua_str(node["name"]), 1 if node["active"] else 0)
    ]


def _emit_block(node, ctx):
    fc = "flowcharts.%s" % node["flowchart"]
    lines = []
    for var in node.get("vars", []):
        lines.append(
            "\tgetvar(%s, %s).value = %s" % (fc, lua_str(var["name"]), _lua_value(var["value"]))
        )
    lines.append("\trunblock(%s, %s)" % (fc, lua_str(node["name"])))
    return lines


# cg 各 action/kind 组合的官方调用（raw_scripts 实证）
_CG_SHOW = {
    "picture": ("runwait(mainui.ShowPicture(%s))", ("key",)),
    "item": ("runwait(mainui.ShowItemPicture(%s))", ("key",)),
    "big": ("runwait(mainui.ShowBigPicture(%s))", ("key",)),
    "map": ("runwait(mainui.ShowMap(%s, %s))", ("key", "key2")),
    "family": ("runwait(mainui.ShowFamilyTree(%s, %s, %s, %s))", ("key", "key2", "n1", "n2")),
    "title": ("mainui.DisplayTitle(%s)", ("key",)),  # 官方 DisplayTitle 无 runwait
}
_CG_HIDE = {
    "picture": "runwait(mainui.HidePicture())",
    "item": "runwait(mainui.HideItemPicture())",
    "big": "runwait(mainui.HideBigPicture())",
    "map": "runwait(mainui.HideMap())",
    "family": "runwait(mainui.HideFamilyTree())",
    # title 无官方 hide API，已在校验阶段拦截
}


def _emit_cg(node, ctx):
    action, kind = node["action"], node["kind"]
    if action == "hide":
        return ["\t" + _CG_HIDE[kind]]
    fmt, arg_names = _CG_SHOW[kind]
    args = [_lua_value(node[k]) for k in arg_names]
    return ["\t" + fmt % tuple(args)]


# ---------------------------------------------------------------------------
# 数值/状态类
# ---------------------------------------------------------------------------


def _emit_stat(node, ctx):
    key = lua_str(node["key"])
    lines = [
        "\tstatmodifymanager.Player(%s, %s, %s, %s)"
        % (
            key,
            lua_num(node["delta"]),
            lua_str(node.get("mode", "")),
            lua_num(node.get("display", 1)),
        )
    ]
    if node.get("waitDisplay", True):
        lines.append("\twait(statmodifymanager.GetDisplayTime(%s))" % key)
    return lines


def _emit_stat_set(node, ctx):
    fn = "UpdateSetPlayerStat" if node.get("update", False) else "SetPlayer"
    return [
        "\tstatmodifymanager.%s(%s, %s)"
        % (fn, lua_str(node["key"]), lua_num(node["value"]))
    ]


def _emit_affinity(node, ctx):
    return [
        "\tstatmodifymanager.Character(%s, %s, 1)"
        % (lua_str(node["character"]), lua_num(node["delta"]))
    ]


def _emit_talent(node, ctx):
    return [
        "\tstatmodifymanager.AddTalent(%s, %s)"
        % (lua_str(node["talent"]), lua_num(node["level"]))
    ]


_ITEM_API = {"book": "Book", "misc": "Misc", "special": "Special"}


def _emit_item(node, ctx):
    api = _ITEM_API[node["kind"]]
    if node.get("remove", False):  # 校验已保证 kind != special
        return ["\tstatmodifymanager.Remove%s(%s)" % (api, lua_str(node["item"]))]
    return [
        "\tstatmodifymanager.Add%s(%s, %s)"
        % (api, lua_str(node["item"]), lua_num(node.get("count", 1)))
    ]


def _emit_flag(node, ctx):
    # 契约 §4：写游戏经历 + 设置 mod 内状态（供 branch source="mod" 判断）
    f = lua_str(node["flag"])
    return [
        "\tstatmodifymanager.AddStory(%s)" % f,
        "\tmodflags[%s] = true" % f,
    ]


def _emit_game_flag(node, ctx):
    fn = "AddFlag" if node.get("op", "set") == "add" else "SetFlag"
    return [
        "\tstatmodifymanager.%s(%s, %s)"
        % (fn, lua_str(node["flag"]), lua_num(node["value"]))
    ]


_ENEMY_API = {
    "team": "ModifyEnemyTeam",
    "level": "ModifyEnemyLevel",
    "people": "ModifyEnemyPeople",
}


def _emit_enemy(node, ctx):
    op = node["op"]
    if op == "id":
        return ["\tstatmodifymanager.ModifyEnemyId(%s)" % lua_str(node["enemy"])]
    return [
        "\tstatmodifymanager.%s(%s, %s, %s)"
        % (
            _ENEMY_API[op],
            lua_str(node["enemy"]),
            lua_num(node["value"]),
            lua_num(node.get("display", 1)),
        )
    ]


def _emit_battle_skill(node, ctx):
    op = node["op"]
    if op == "reset":
        return ["\tluamanager.ResetBattleSkill()"]
    if op == "active":
        return [
            "\tluamanager.SetBattleSkillActive(%s, %s)"
            % (lua_str(node["key"]), lua_num(node.get("active", 1)))
        ]
    return [
        "\tluamanager.SetPlayerBattleSkill(%s, %s)"
        % (lua_str(node["key"]), lua_num(node.get("index", 2)))
    ]


def _emit_mission(node, ctx):
    return [
        "\tstatmodifymanager.Mission(%s, %s)"
        % (lua_str(node["name"]), lua_str(node["key"]))
    ]


def _emit_time(node, ctx):
    op = node["op"]
    if op == "round":
        return ["\tluamanager.NextRound()"]
    if op == "month":
        return ["\tluamanager.NextMonth()"]
    if op == "mission":
        return [
            "\tluamanager.SetMissionTime(%s, %s, %s, %s)"
            % (
                lua_str(node["name"]),
                lua_num(node["year"]),
                lua_num(node["month"]),
                lua_num(node["stage"]),
            )
        ]
    return [
        "\tluamanager.SetGameTime(%s, %s, %s)"
        % (lua_num(node["year"]), lua_num(node["month"]), lua_num(node["stage"]))
    ]


def _emit_autosave(node, ctx):
    kind = node.get("kind", "story")
    lines = []
    if kind == "free":
        lines.append("\tluamanager.AutoFreeSave()")
    elif kind == "prologue":
        # 契约 §3.1 写作 PrologueSave(mode) 但未给 mode 字段；官方两处分别
        # 传 1/0（序幕首尾），语义不明，固定取 0（见契约歧义说明）
        lines.append("\tluamanager.PrologueSave(0)")
    else:
        lines.append("\tluamanager.AutoSave()")
    if "save_button" in node:
        lines.append("\tluamanager.ToggleSaveButton(%d)" % node["save_button"])
    return lines


# ---------------------------------------------------------------------------
# 流程类
# ---------------------------------------------------------------------------


def _emit_branch(node, ctx):
    """分支（契约 §4，两种 source；未命中必须有 else 兜底）。

    ctx["next_id"] 为顺序下一节点 id，作为 else 的默认落点；
    校验已保证需要兜底时 next_id 一定存在。
    """
    source = node.get("source", "mod")
    flag = lua_str(node["flag"])
    next_id = ctx.get("next_id")
    if source == "mod":
        # 按 modflags[flag] 是否已设置二分：value 1=已设置(then)，2=未设置(else)；
        # 缺某一路时该路落顺序下一节点。
        cases = {c["value"]: c["goto"] for c in node["cases"]}
        then_goto = cases.get(1, next_id)
        else_goto = cases.get(2, next_id)
        return [
            "\tif modflags[%s] then" % flag,
            "\t\treturn node_%s()" % then_goto,
            "\telse",
            "\t\treturn node_%s()" % else_goto,
            "\tend",
        ]
    # source="game"：读官方检查点，Switch 找不到时返回 0，else 兜底落顺序下一节点
    lines = ["\tlocal branch1 = checkpointmanager.Switch(%s)" % flag]
    for i, case in enumerate(node["cases"]):
        kw = "if" if i == 0 else "elseif"
        lines.append("\t%s branch1 == %s then" % (kw, lua_num(case["value"])))
        lines.append("\t\treturn node_%s()" % case["goto"])
    lines.append("\telse")
    lines.append("\t\treturn node_%s()" % next_id)
    lines.append("\tend")
    return lines


def _emit_dice(node, ctx):
    """骰子检定：官方五步链 + ResultSelection 三向分支（契约 §4，v1 简化）。

    三向统一取第 1 个 option 的 goto_大成功/成功/失败（契约有歧义，见返回说明）。
    """
    check = lua_str(node["check"])
    first = node["options"][0]
    lines = [
        "\tsetmenudialog(menudialogs.Dice)",
        "\tlocal dice_rand1 = math.random(99)",
        "\tdicemenudialog.SetRandom(99, dice_rand1)",
        "\tlocal dice_result1 = checkpointmanager.Dice(%s, dice_rand1)" % check,
        "\tlocal dice_opts1 = {}",
    ]
    for i, opt in enumerate(node["options"], 1):
        # 契约 §4 菜单项格式："选项一|<33"。游戏把 | 前文本当作本地化 key
        # 解析（DiceOption.UpdateContent → GetStoryText，查不到时原样返回），
        # 分隔符必须保留；文本里的 ASCII 竖线换成全角 "｜" 防格式破坏。
        text = str(opt["text"]).replace("|", "｜")
        entry = "%s|<%s" % (text, lua_num(opt["threshold"]))
        lines.append("\tdice_opts1[%d] = %s" % (i, lua_str(entry)))
    lines += [
        "\tdicemenudialog.Setup(dice_result1.ResultCount, dice_result1.Result, "
        "dice_result1.Header, dice_result1.Additions)",
        "\trunwait(dicemenudialog.ExecuteRoll(dice_opts1, 1, %s))" % check,
        "\tlocal dice_sel1 = dicemenudialog.ResultSelection",
        "\tif dice_sel1 == 1 then",
        "\t\treturn node_%s()" % first["goto_大成功"],
        "\telseif dice_sel1 == 2 then",
        "\t\treturn node_%s()" % first["goto_成功"],
        "\telse",
        "\t\treturn node_%s()" % first["goto_失败"],
        "\tend",
    ]
    return lines


def _emit_goto_scene(node, ctx):
    return [
        "\tluamanager.ChangeScene(%s, %s, %s)"
        % (
            lua_str(node["scene"]),
            lua_str(node.get("key", "")),
            lua_str(node.get("next", "Story")),
        )
    ]


def _emit_panel(node, ctx):
    p = node["panel"]
    if p == "martial":
        return ["\trunwait(martialpanel.Open(%s))" % lua_num(node.get("mode", 0))]
    if p == "weapon":
        return ["\trunwait(weaponupgradepanel.Open())"]
    if p == "poison":
        return ["\trunwait(poisonupgradepanel.Open())"]
    if p == "cg":
        return ["\trunwait(cgpanel.Open(%s))" % lua_str(node["key"])]
    if p == "cgvideo":
        return ["\trunwait(cgvideopanel.Open(%s, 0))" % lua_str(node["key"])]
    if p == "shop":
        return ["\trunwait(shoppanel.Open(%s))" % lua_num(node.get("discount", 0))]
    if p == "newshop":  # 契约 §3.1：除 newshop 外均 runwait
        return ["\tshoppanel.NewShop()"]
    if p == "credit":
        return ["\trunwait(creditpanel.Open())"]
    # endgame
    return ["\trunwait(endgamepanel.Open(%s))" % lua_str(node["key"])]


def _emit_wait(node, ctx):
    return ["\twait(%s)" % lua_num(node["seconds"])]


def _emit_end(node, ctx):
    next_script = node.get("next_script")
    if next_script is None:
        # 无 next_script：官方标准收尾，返回自由模式（契约 §3.1）。
        # 注意不能 emit luamanager.Init()：无后续脚本时 Init 会重跑当前
        # 脚本，造成死循环。
        return ['\tluamanager.ChangeScene("Free", "", "")']
    # 有 next_script：链到同包内另一脚本。运行时注册名带 MOD_<modid>_
    # 前缀（契约 §3.1/§6）；裸 build 不知 mod id 时退化为原始脚本 id。
    target = (
        "MOD_%s_%s" % (ctx["mod_id"], next_script)
        if ctx.get("mod_id")
        else next_script
    )
    return [
        "\tluamanager.SetNextScript(%s)" % lua_str(target),
        "\tluamanager.Init()",
    ]


def _emit_raw(node, ctx):
    # 原生 Lua 逃逸口：原样插入（契约 §4）。
    # 不加缩进——code 里可能含 [[...]] 长字符串，改动空白会改变内容。
    return node["code"].splitlines()


_EMITTERS = {
    "music": _emit_music,
    "sound": _emit_sound,
    "scene": _emit_scene,
    "show": _emit_show,
    "move": _emit_move,
    "face": _emit_face,
    "hide": _emit_hide,
    "focus": _emit_focus,
    "offset": _emit_offset,
    "say": _emit_say,
    "choice": _emit_choice,
    "shock": _emit_shock,
    "mask": _emit_mask,
    "intro": _emit_intro,
    "effect": _emit_effect,
    "transition": _emit_transition,
    "camera": _emit_camera,
    "block": _emit_block,
    "cg": _emit_cg,
    "stat": _emit_stat,
    "stat_set": _emit_stat_set,
    "affinity": _emit_affinity,
    "talent": _emit_talent,
    "item": _emit_item,
    "flag": _emit_flag,
    "game_flag": _emit_game_flag,
    "enemy": _emit_enemy,
    "battle_skill": _emit_battle_skill,
    "mission": _emit_mission,
    "time": _emit_time,
    "autosave": _emit_autosave,
    "branch": _emit_branch,
    "dice": _emit_dice,
    "goto_scene": _emit_goto_scene,
    "panel": _emit_panel,
    "wait": _emit_wait,
    "end": _emit_end,
    "raw": _emit_raw,
}

# 自带流转（分支/跳转），story_to_lua 不再追加 return node_<goto>() 行
_NO_FLOW_TYPES = ("end", "choice", "branch", "dice", "goto_scene")


def story_to_lua(story, mod_info=None, source=None):
    """把已校验的 story dict 编译为 Lua 源码字符串。

    mod_info：可选的 manifest dict（pack 时传入），用于文件头注释与
    end 节点 SetNextScript 的 MOD_<modid>_ 前缀。
    source：可选的来源描述（通常是 story/<id>.json），写进文件头注释。
    """
    ctx = {"mod_id": mod_info.get("id") if mod_info else None}
    nodes = story["nodes"]

    lines = [GENERATED_MARK]
    src = source or ("story/%s.json" % story["id"])
    title = story.get("title", "")
    lines.append("-- Source: %s (id=%s, title=%s)" % (src, story["id"], title))
    if mod_info:
        lines.append(
            "-- Mod: %s (%s) v%s by %s"
            % (
                mod_info.get("id", ""),
                mod_info.get("name", ""),
                mod_info.get("version", ""),
                mod_info.get("author", ""),
            )
        )
    lines.append("")

    # 契约 §4：每个脚本开头初始化 mod 内 flag 表（全局表，链式脚本间共享）
    lines.append("-- mod 内剧情 flag 表（不存档，重进游戏清零）")
    lines.append("modflags = modflags or {}")
    lines.append("")

    # 前向声明全部节点函数：Lua 的 local function 无法引用后定义的 local，
    # 而汇合点 / 分支回环要求任意方向的跳转。
    lines.append("-- 节点函数前向声明（支持任意 goto / 分支回环）")
    lines.append("local " + ", ".join("node_%s" % n["id"] for n in nodes))
    lines.append("")

    for i, node in enumerate(nodes):
        lines.append("-- [%s] %s" % (node["id"], node["type"]))
        lines.append("node_%s = function()" % node["id"])
        emitter = _EMITTERS.get(node["type"])
        if emitter is None:
            raise LomcError(
                '内部错误：节点 "%s" 类型 "%s" 未校验通过' % (node["id"], node["type"])
            )
        # branch 的 else 兜底需要顺序下一节点 id（校验已保证需要时存在）
        ctx["next_id"] = nodes[i + 1]["id"] if i + 1 < len(nodes) else None
        lines.extend(emitter(node, ctx))
        if node["type"] not in _NO_FLOW_TYPES:
            # 显式 goto 覆盖顺序流（契约 §3）；校验已保证目标存在
            goto = node.get("goto")
            if goto is None:
                goto = nodes[i + 1]["id"]
            lines.append("\treturn node_%s()" % goto)
        lines.append("end")
        lines.append("")

    lines.append("return node_%s()" % story["start"])
    return "\n".join(lines) + "\n"
