# -*- coding: utf-8 -*-
"""Folder projects keep independently saved chapters together across reopen."""
from __future__ import annotations

import copy
import json
import os
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
EDITOR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(EDITOR))

from PySide6.QtWidgets import QApplication  # noqa: E402

import main  # noqa: E402
import models  # noqa: E402
from recovery_store import RecoverySession, list_recovery_candidates  # noqa: E402


class Preferences:
    def __init__(self):
        self.values = {}

    def load_pref(self, key):
        return self.values.get(key)

    def save_pref(self, key, value):
        self.values[key] = value


class FolderProjectTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.win = main.MainWindow(models.FALLBACK_EDITOR_DATA, True)
        self.win._prompt_on_discard = False
        self.win.game_manager = Preferences()
        self.errors = patch("project_controller.QMessageBox.critical")
        self.error = self.errors.start()

    def tearDown(self):
        self.win._prompt_on_discard = False
        self.win.close()
        self.win.deleteLater()
        self.app.processEvents()
        self.errors.stop()
        self.temp.cleanup()

    def chapter(self, sid, directory=None, filename=None):
        directory = directory or self.root
        path = directory / (filename or f"{sid}.json")
        story = {
            "story_schema": 2, "id": sid, "title": f"章节 {sid}",
            "start": "say1", "mood": False,
            "nodes": [{"id": "say1", "type": "say", "mode": "center", "text": sid},
                      {"id": "end1", "type": "end"}],
        }
        models.save_story(story, path)
        return path

    def three_chapters(self):
        for sid in ("main", "story2", "story3"):
            self.chapter(sid)
        (self.root / "qunfangpu.lommod").write_bytes(b"unrelated package")

    def test_flat_folder_loads_all_chapters_and_keeps_original_paths(self):
        self.three_chapters()
        self.assertTrue(self.win._load_story_folder(self.root))
        self.assertEqual(set(self.win._stories), {"main", "story2", "story3"})
        self.assertEqual(self.win.story_combo.count(), 3)
        self.assertEqual(self.win._current_id, "main")
        self.assertEqual(self.win._story_paths["story2"], self.root / "story2.json")
        self.assertFalse(self.win._dirty)

    def test_switch_save_all_and_reopen_keeps_every_chapter_edit(self):
        self.three_chapters()
        self.win._load_story_folder(self.root)
        for sid in ("main", "story2", "story3"):
            self.win.story_combo.setCurrentIndex(self.win.story_combo.findData(sid))
            self.win.story["nodes"][0]["text"] = f"修改 {sid}"
        self.win._set_dirty(True)
        self.assertTrue(self.win.save_story())
        self.assertFalse(self.win._dirty)
        self.assertTrue(self.win._load_story_folder(self.root))
        for sid in ("main", "story2", "story3"):
            self.assertEqual(self.win._stories[sid]["nodes"][0]["text"], f"修改 {sid}")

    def test_folder_keeps_cross_chapter_targets_and_compiles_each_story(self):
        self.three_chapters()
        for sid, following in (("main", "story2"), ("story2", "story3")):
            path = self.root / f"{sid}.json"
            story = models.load_story(path)
            story["nodes"][-1]["next_script"] = following
            models.save_story(story, path)
        self.assertTrue(self.win._load_story_folder(self.root))
        self.assertEqual(self.win._stories["main"]["nodes"][-1]["next_script"], "story2")
        self.assertEqual(self.win._stories["story2"]["nodes"][-1]["next_script"], "story3")
        for story in self.win._stories.values():
            lua, error = main.compile_story(story)
            self.assertIsNone(error)
            self.assertTrue(lua.startswith("-- Generated by lomc"))

    def test_standard_project_preserves_manifest_and_uses_its_entry(self):
        self.chapter("main", self.root / "story")
        self.chapter("event", self.root / "story")
        manifest = {"entry": "event", "campaign_id": "unchanged",
                    "campaign": {"new_game": True, "triggers": []},
                    "name": "原有项目"}
        (self.root / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
        (self.root / "editor-settings.json").write_text('{"theme":"dark"}', encoding="utf-8")
        self.assertTrue(self.win._load_story_folder(self.root))
        self.assertEqual(self.win._current_id, "event")
        self.assertEqual(self.win.manifest_base, manifest)
        self.win._add_story_in_project()
        new_id = self.win._current_id
        self.assertTrue(self.win.save_story())
        self.assertTrue((self.root / "story" / f"{new_id}.json").is_file())
        self.assertEqual(json.loads((self.root / "manifest.json").read_text()), manifest)

    def test_duplicate_ids_report_both_files_without_replacing_current_project(self):
        self.chapter("main")
        self.chapter("main", filename="story2.json")
        before = self.win._snapshot()
        self.assertFalse(self.win._load_story_folder(self.root))
        self.assertEqual(self.win._snapshot(), before)
        message = self.error.call_args.args[-1]
        self.assertIn("main.json", message)
        self.assertIn("story2.json", message)

    def test_malformed_chapter_does_not_partially_open_a_folder(self):
        self.chapter("main")
        (self.root / "story2.json").write_text('{"nodes":', encoding="utf-8")
        before = self.win._snapshot()
        self.assertFalse(self.win._load_story_folder(self.root))
        self.assertEqual(self.win._snapshot(), before)
        self.assertIn("story2.json", self.error.call_args.args[-1])

    def test_empty_folder_has_an_explicit_error(self):
        self.assertFalse(self.win._load_story_folder(self.root))
        self.error.assert_called_once()

    def test_invalid_manifest_entry_does_not_replace_the_current_project(self):
        self.chapter("main")
        (self.root / "manifest.json").write_text('{"entry":{}}', encoding="utf-8")
        before = self.win._snapshot()
        self.assertFalse(self.win._load_story_folder(self.root))
        self.assertEqual(self.win._snapshot(), before)
        self.assertIn("entry", self.error.call_args.args[-1])

    def test_folder_picker_cancel_leaves_dirty_project_untouched(self):
        self.win.story["title"] = "尚未保存"
        self.win._set_dirty(True)
        before = self.win._snapshot()
        with patch("project_controller.QFileDialog.getExistingDirectory", return_value=""), \
                patch.object(self.win, "_confirm_discard") as confirm:
            self.win.open_story_folder()
        confirm.assert_not_called()
        self.assertEqual(self.win._snapshot(), before)
        self.assertTrue(self.win._dirty)

    def test_folder_picker_respects_cancel_of_unsaved_changes(self):
        self.three_chapters()
        before = self.win._snapshot()
        with patch("project_controller.QFileDialog.getExistingDirectory", return_value=str(self.root)), \
                patch.object(self.win, "_confirm_discard", return_value=False):
            self.win.open_story_folder()
        self.assertEqual(self.win._snapshot(), before)

    def test_recent_and_startup_restore_folder_and_selected_chapter(self):
        self.three_chapters()
        with patch.object(self.win, "_should_persist_session", return_value=True):
            self.win._load_story_folder(self.root)
            self.win.story_combo.setCurrentIndex(self.win.story_combo.findData("story3"))
            self.assertEqual(self.win.game_manager.load_pref("last_open_kind"), "folder")
            self.assertEqual(self.win._load_recents()[0]["kind"], "folder")
            self.win.new_story()
            self.assertTrue(self.win.restore_last_project())
            self.assertEqual(self.win._current_id, "story3")
            self.assertEqual(self.win.story_combo.count(), 3)
            self.win._open_recent("folder", str(self.root))
            self.assertEqual(self.win.story_combo.count(), 3)

    def test_first_multi_chapter_save_chooses_one_folder(self):
        self.win._add_story_in_project()
        sid = self.win._current_id
        with patch("project_controller.QFileDialog.getExistingDirectory", return_value=str(self.root)), \
                patch("project_controller.QFileDialog.getSaveFileName") as single:
            self.assertTrue(self.win.save_story())
        single.assert_not_called()
        self.assertTrue((self.root / "main.json").is_file())
        self.assertTrue((self.root / f"{sid}.json").is_file())
        self.assertTrue((self.root / "manifest.json").is_file())
        manifest = copy.deepcopy(self.win.manifest_base)
        self.assertTrue(self.win._load_story_folder(self.root))
        self.assertEqual(self.win.manifest_base, manifest)

    def test_save_failure_keeps_dirty_state_and_reports_failed_file(self):
        self.three_chapters()
        self.win._load_story_folder(self.root)
        self.win._stories["story2"]["title"] = "未保存的章节二"
        self.win._set_dirty(True)
        before = (self.root / "story2.json").read_bytes()
        with patch("project_controller.models.save_story", side_effect=OSError("write denied")):
            self.assertFalse(self.win.save_story())
        self.assertTrue(self.win._dirty)
        self.assertEqual((self.root / "story2.json").read_bytes(), before)
        self.error.assert_called_once()

    def test_save_as_copies_all_chapters_to_another_folder(self):
        self.three_chapters()
        self.win._load_story_folder(self.root)
        target = self.root / "copy"
        target.mkdir()
        with patch("project_controller.QFileDialog.getExistingDirectory", return_value=str(target)):
            self.assertTrue(self.win.save_story_as())
        self.assertTrue(self.win._load_story_folder(target))
        self.assertEqual(set(self.win._stories), {"main", "story2", "story3"})

    def test_save_to_unrelated_files_does_not_overwrite_them(self):
        self.win._add_story_in_project()
        existing = self.chapter("main")
        before = existing.read_bytes()
        self.assertFalse(self.win._write_story_folder(self.root))
        self.assertEqual(existing.read_bytes(), before)
        self.assertTrue(self.win._dirty)

    def test_renaming_and_undo_reuse_the_original_chapter_file(self):
        self.three_chapters()
        self.win._load_story_folder(self.root)
        self.win.story_id_edit.setText("renamed")
        self.win._on_story_props_changed()
        self.assertEqual(self.win._current_id, "renamed")
        self.assertTrue(self.win.save_story())
        self.assertFalse((self.root / "renamed.json").exists())
        self.assertEqual(models.load_story(self.root / "main.json")["id"], "renamed")
        self.win._undo()
        self.assertEqual(self.win._current_id, "main")
        self.assertTrue(self.win.save_story())
        self.assertEqual(models.load_story(self.root / "main.json")["id"], "main")

    def test_folder_recovery_preserves_all_chapters_without_writing_formal_files(self):
        self.three_chapters()
        self.win._load_story_folder(self.root)
        before = (self.root / "main.json").read_bytes()
        self.win._recovery_session = RecoverySession(self.root / "recovery", "test")
        self.win.story["title"] = "恢复副本"
        self.win._set_dirty(True)
        self.win._autosave_recovery()
        candidates = list_recovery_candidates(self.root / "recovery", include_live=True)
        self.assertEqual(len(candidates), 1)
        self.assertEqual(candidates[0].source_kind, "folder")
        self.assertEqual(set(candidates[0].story_ids), {"main", "story2", "story3"})
        self.assertEqual((self.root / "main.json").read_bytes(), before)


if __name__ == "__main__":
    unittest.main()
