# -*- coding: utf-8 -*-
import copy
from pathlib import Path
import sys
import unittest

EDITOR = Path(__file__).resolve().parent.parent
COMPILER = EDITOR.parent / "compiler"
sys.path[:0] = [str(EDITOR), str(COMPILER)]

import models
from lomc import compile_story, validate_story
from project_templates import TEMPLATES, create_project_template


class ProjectTemplatesTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.editor_data, _ = models.load_editor_data(EDITOR.parent)

    def test_all_five_templates_are_plain_compilable_story_schema(self):
        self.assertEqual(
            [item.key for item in TEMPLATES],
            ["empty", "linear_dialogue", "branching_story",
             "custom_character_showcase", "user_content_showcase"],
        )
        allowed = {"story_schema", "id", "title", "mood", "start", "nodes"}
        for item in TEMPLATES:
            with self.subTest(item.key):
                project = create_project_template(item.key, self.editor_data)
                self.assertEqual(project["current_story_id"], "main")
                self.assertRegex(
                    project["manifest"]["campaign_id"], r"^[a-z0-9_-]{1,64}$"
                )
                self.assertEqual(
                    project["manifest"]["campaign"], {"new_game": True}
                )
                story = project["stories"]["main"]
                self.assertEqual(set(story), allowed)
                validate_story(story, source="template:" + item.key)
                lua = compile_story(story)
                self.assertIn("-- Generated by lomc", lua)
                self.assertEqual(story["nodes"][-1]["type"], "end")

    def test_instances_are_independent_and_placeholders_are_explicit(self):
        first = create_project_template("custom_character_showcase", self.editor_data)
        second = create_project_template("custom_character_showcase", self.editor_data)
        first["stories"]["main"]["nodes"][0]["character"] = "changed"
        self.assertEqual(
            second["stories"]["main"]["nodes"][0]["character"],
            "user:template.hero",
        )
        media = create_project_template("user_content_showcase", self.editor_data)
        serialized = repr(media)
        for suffix in ("background", "music", "sound", "cg", "voice"):
            self.assertIn("user:template." + suffix, serialized)


if __name__ == "__main__":
    unittest.main()
