//! Optional cross-language corpus audit. Input is generated by the legacy
//! test_watermark_detector / test_watermark_video_detector fixture builders.
//! No Python interpreter or image corpus is required for normal native tests.
use lom_core::watermark::{detect_image, detect_video_frames};
use serde_json::Value;
use std::path::PathBuf;
#[test]
#[ignore = "requires LOM_WATERMARK_CORPUS pointing to the generated legacy corpus"]
fn original_python_image_and_video_corpus() {
    let root =
        PathBuf::from(std::env::var_os("LOM_WATERMARK_CORPUS").expect("LOM_WATERMARK_CORPUS"));
    let expected: Value =
        serde_json::from_slice(&std::fs::read(root.join("expected.json")).unwrap()).unwrap();
    for (name, filename, scale) in [
        ("original", "original.png", 1.),
        ("jpeg", "jpeg.jpg", 1.),
        ("resize", "resize.png", 0.75),
        ("mild_crop", "mild_crop.png", 1.),
        ("brightness", "brightness.png", 1.),
        ("contrast", "contrast.png", 1.),
        ("clean_negative", "clean_negative.png", 1.),
    ] {
        let actual = detect_image(&root.join(filename), &[scale]).unwrap();
        compare(name, &actual, &expected[name]);
    }
    for (name, prefix) in [("video_marked", "marked"), ("video_clean", "clean")] {
        let frames = (0..4)
            .map(|i| root.join(format!("{prefix}-{i:02}.png")))
            .collect::<Vec<_>>();
        let actual = detect_video_frames(&frames, 2., &[1.]).unwrap();
        compare(name, &actual, &expected[name]);
    }
}
fn compare(name: &str, actual: &Value, expected: &Value) {
    for key in [
        "detected",
        "protocol_version",
        "algorithm_version",
        "mod_hash",
        "checksum_status",
        "ecc_status",
        "ecc_corrections",
        "scale_factor",
    ] {
        assert_eq!(actual[key], expected[key], "{name}: {key}; actual {actual}");
    }
    for key in ["confidence", "sync_score"] {
        let a = actual[key].as_f64().unwrap();
        let e = expected[key].as_f64().unwrap();
        assert!((a - e).abs() < 0.00001, "{name}: {key}: {a} vs {e}");
    }
    println!("{name}: {actual}");
}
