# -*- coding: utf-8 -*-
"""lomc 单元测试（stdlib unittest）。

运行方式（在 compiler/ 目录下）：
    python -m unittest tests.test_lomc -v
"""

import json
import os
import subprocess
import sys
import tempfile
import unittest
import zipfile

from lomc import (
    LomcError,
    compile_story,
    pack_mod,
    validate_manifest,
    validate_story,
)

COMPILER_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MANIFEST = {
    "format": 1,
    "id": "testmod",
    "name": "测试 Mod",
    "version": "0.1.0",
    "author": "tester",
    "description": "单元测试用",
    "entry": "main",
}


def make_story(nodes, story_id="main", start=None, title="测试剧情"):
    """构造合法 story dict 的便捷函数。"""
    return {
        "id": story_id,
        "title": title,
        "start": start or nodes[0]["id"],
        "nodes": nodes,
    }


def linear_story(*extra_nodes):
    """若干节点 + end 结尾的线性好故事。"""
    nodes = list(extra_nodes) + [{"id": "nend", "type": "end"}]
    return make_story(nodes)


def assert_compile_error(testcase, story, *keywords):
    """断言编译抛 LomcError，且消息包含全部关键词。"""
    with testcase.assertRaises(LomcError) as cm:
        compile_story(story)
    msg = str(cm.exception)
    for kw in keywords:
        testcase.assertIn(kw, msg)
    return msg


# ---------------------------------------------------------------------------
# 合法脚本编译
# ---------------------------------------------------------------------------


class TestCompileValid(unittest.TestCase):
    def test_header_and_structure(self):
        lua = compile_story(
            linear_story({"id": "n1", "type": "music", "name": "普通_001"}),
            mod_info=MANIFEST,
            source="story/main.json",
        )
        lines = lua.splitlines()
        self.assertEqual(lines[0], "-- Generated by lomc, do not edit")
        self.assertIn("-- Source: story/main.json (id=main, title=测试剧情)", lines[1])
        self.assertIn("-- Mod: testmod (测试 Mod) v0.1.0 by tester", lines[2])
        # 前向声明 + 函数定义 + 顶层入口
        self.assertIn("local node_n1, node_nend", lua)
        self.assertIn("node_n1 = function()", lua)
        self.assertEqual(lines[-1], "return node_n1()")
        # 契约 §4：脚本开头初始化 mod 内 flag 表（在前向声明之前）
        self.assertIn("modflags = modflags or {}", lines)
        self.assertLess(
            lines.index("modflags = modflags or {}"),
            lines.index("local node_n1, node_nend"),
        )
        # 契约 §4：mood 声明（story 顶层 mood 默认 false）紧跟 modflags 行
        self.assertIn("mod_set_mood(false)", lines)
        self.assertEqual(
            lines.index("mod_set_mood(false)"),
            lines.index("modflags = modflags or {}") + 1,
        )

    def test_implicit_and_explicit_goto(self):
        lua = compile_story(
            linear_story(
                {"id": "n1", "type": "music", "name": "普通_001"},
                {"id": "n2", "type": "focus", "character": "player"},
            )
        )
        # 顺序流：n1 隐式流向 n2
        self.assertIn("\treturn node_n2()", lua)
        # 显式 goto 覆盖顺序流
        lua2 = compile_story(
            linear_story(
                {"id": "n1", "type": "music", "name": "普通_001", "goto": "nend"},
                {"id": "n2", "type": "focus", "character": "player"},
            )
        )
        self.assertIn("\treturn node_nend()", lua2)

    def test_string_escape(self):
        # 转义覆盖改在 music 名称上验（say 文本已不再裸字面量进 Lua，改走已读 key）
        lua = compile_story(
            linear_story(
                {
                    "id": "n1",
                    "type": "music",
                    "name": '反斜杠\\引号"换行\n第二行',
                }
            )
        )
        self.assertIn('luamanager.PlayMusic("反斜杠\\\\引号\\"换行\\n第二行")', lua)

    def test_number_format(self):
        lua = compile_story(
            linear_story(
                {"id": "n1", "type": "stat", "key": "mental", "delta": -5},
                {"id": "n2", "type": "wait", "seconds": 1.5},
                {"id": "n3", "type": "wait", "seconds": 2.0},
            )
        )
        self.assertIn('statmodifymanager.Player("mental", -5, "", 1)', lua)
        self.assertIn("\twait(1.5)", lua)
        self.assertIn("\twait(2)", lua)  # 整数值不带小数点


# ---------------------------------------------------------------------------
# 各节点类型 codegen 关键片段（逐条对照契约 §4）
# ---------------------------------------------------------------------------


class TestNodeCodegen(unittest.TestCase):
    def lua_of(self, node, mod_info=None):
        return compile_story(linear_story(node), mod_info=mod_info)

    def test_music(self):
        lua = self.lua_of({"id": "n1", "type": "music", "name": "普通_001"})
        self.assertIn('\tluamanager.PlayMusic("普通_001")', lua)

    def test_scene(self):
        lua = self.lua_of({"id": "n1", "type": "scene", "view": "center"})
        self.assertIn('\trunblock(flowcharts.view, "out")', lua)
        self.assertIn('\tgetvar(flowcharts.view, "ViewName").value = "center"', lua)
        self.assertIn('\trunblock(flowcharts.view, "view")', lua)

    def test_scene_out_only(self):
        lua = self.lua_of({"id": "n1", "type": "scene", "view": "out"})
        self.assertIn('\trunblock(flowcharts.view, "out")', lua)
        self.assertNotIn("ViewName", lua)
        self.assertNotIn('runblock(flowcharts.view, "view")', lua)

    def test_show(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "show",
                "character": "player",
                "position": "RM2",
                "portrait": "nervous1",
                "facing": "left",
                "fadeDuration": 0.5,
                "moveDuration": 2,
            }
        )
        self.assertIn('\trunwait(characters.LoadCharacterAsset("player"))', lua)
        self.assertIn(
            '\tstage.show{character=characters.Get("player"), '
            'portrait=characters.GetPortrait("player", "nervous1"), '
            'fromPosition="RM2", toPosition="RM2", facing="left", '
            "fadeDuration=0.5, moveDuration=2, useDefaultSettings=false}",
            lua,
        )
        self.assertIn('\tcharacters.Focus("player")', lua)

    def test_show_defaults(self):
        lua = self.lua_of(
            {"id": "n1", "type": "show", "character": "player", "position": "M"}
        )
        self.assertIn('portrait=characters.GetPortrait("player", "normal")', lua)
        self.assertIn('facing="right"', lua)
        self.assertIn("fadeDuration=0, moveDuration=0", lua)

    def test_move(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "move",
                "character": "player",
                "from": "RM2",
                "to": "R2",
                "duration": 0.3,
            }
        )
        self.assertIn(
            '\tstage.show{character=characters.Get("player"), fromPosition="RM2", '
            'toPosition="R2", moveDuration=0.3, useDefaultSettings=false}',
            lua,
        )
        self.assertIn("\twait(0.3)", lua)

    def test_move_default_duration(self):
        lua = self.lua_of(
            {"id": "n1", "type": "move", "character": "p", "from": "M", "to": "R1"}
        )
        self.assertIn("moveDuration=1", lua)
        self.assertIn("\twait(1)", lua)

    def test_face(self):
        lua = self.lua_of(
            {"id": "n1", "type": "face", "character": "player", "facing": "left"}
        )
        self.assertIn(
            '\tstage.show{character=characters.Get("player"), facing="left", '
            "useDefaultSettings=false}",
            lua,
        )

    def test_hide(self):
        lua = self.lua_of({"id": "n1", "type": "hide", "character": "trainee1"})
        self.assertIn(
            '\tstage.hide{character=characters.Get("trainee1"), fadeDuration=0, '
            "useDefaultSettings=false}",
            lua,
        )

    def test_focus(self):
        lua = self.lua_of({"id": "n1", "type": "focus", "character": "brother4"})
        self.assertIn('\tcharacters.Focus("brother4")', lua)

    def test_say_character(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "say",
                "character": "player",
                "portrait": "nervous1",
                "text": "对话文本",
            }
        )
        self.assertIn("\tsetsaydialog(saydialogs.character)", lua)
        self.assertIn("\tsayoptions.waitforinput = true", lua)
        self.assertIn("\tsayoptions.fadewhendone  = true", lua)
        self.assertIn(
            '\tstage.showPortrait(characters.Get("player"), '
            'characters.GetPortrait("player", "nervous1"))',
            lua,
        )
        self.assertIn(
            '\tsetcharacter(characters.Get("player"), '
            'characters.GetPortrait("player", "nervous1"))',
            lua,
        )
        self.assertIn('\tcharacters.Focus("player")', lua)
        # 已读系统：say 发射 GetStoryText(key)，不再裸字面量（key 默认 MOD 兜底）
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_MOD_main_n1"))', lua)
        self.assertNotIn("对话文本", lua)
        self.assertNotIn("os_mask", lua)

    def test_say_think(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "say",
                "mode": "think",
                "character": "player",
                "text": "内心独白",
            }
        )
        self.assertIn("\tsetsaydialog(saydialogs.think)", lua)
        self.assertIn("\tos_mask.SetLastPosition()", lua)
        self.assertIn("\tos_mask.Show(true)", lua)
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_MOD_main_n1"))', lua)
        self.assertIn("\tos_mask.Show(false)", lua)
        # 顺序：Show(true) 在 say 前，Show(false) 在 say 后
        say_line = 'say(luamanager.GetStoryText("MOD_MOD_main_n1"))'
        self.assertLess(lua.index("os_mask.Show(true)"), lua.index(say_line))
        self.assertLess(lua.index(say_line), lua.index("os_mask.Show(false)"))

    def test_say_narrative(self):
        lua = self.lua_of(
            {"id": "n1", "type": "say", "mode": "narrative", "text": "旁白"}
        )
        self.assertIn("\tsetsaydialog(saydialogs.narrative)", lua)
        # 官方 ch1_1 实证：任何 say 前都设 sayoptions（否则等待输入行为取决于环境默认）
        self.assertIn("\tsayoptions.waitforinput = true", lua)
        self.assertIn("\tsayoptions.fadewhendone  = true", lua)
        self.assertIn("\tsetcharacter(narrative)", lua)
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_MOD_main_n1"))', lua)
        self.assertNotIn("showPortrait", lua)

    def test_say_center(self):
        lua = self.lua_of({"id": "n1", "type": "say", "mode": "center", "text": "居中"})
        self.assertIn("\tsetsaydialog(saydialogs.center)", lua)
        self.assertIn("\tsayoptions.waitforinput = true", lua)
        self.assertIn("\tsetcharacter(narrative)", lua)
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_MOD_main_n1"))', lua)

    def test_say_key_with_mod_info(self):
        # 打包时 mod_id 来自 manifest：key = MOD_<modid>_<scriptid>_<nodeid>
        lua = self.lua_of(
            {"id": "n1", "type": "say", "mode": "narrative", "text": "打包文本"},
            mod_info=MANIFEST,
        )
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_testmod_main_n1"))', lua)

    def test_mood_hide_default(self):
        # story.mood 缺省 false：发射 mod_set_mood(false)；show 末尾 / say 前后各发射一次 mod_hide_mood()
        lua = compile_story(
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "show",
                        "character": "player",
                        "position": "M",
                    },
                    {"id": "n2", "type": "say", "mode": "narrative", "text": "台词"},
                    {"id": "nend", "type": "end"},
                ]
            )
        )
        self.assertEqual(lua.count("mod_hide_mood()"), 3)
        # mood 声明：默认 false 发射在脚本头部（与 modflags 相邻）
        self.assertIn("mod_set_mood(false)", lua)
        self.assertNotIn("mod_set_mood(true)", lua)
        # show：Focus 之后（首个 hide 在 show 块里）
        self.assertLess(
            lua.index('characters.Focus("player")'),
            lua.index("mod_hide_mood()"),
        )
        # say：hide 在 GetStoryText 前，say 后紧跟 hide
        i = lua.index('say(luamanager.GetStoryText("MOD_MOD_main_n2"))')
        self.assertGreater(i, lua.rindex("mod_hide_mood()", 0, i))
        self.assertGreater(lua.index("mod_hide_mood()", i), i)

    def test_mood_true_keeps_bubbles(self):
        # story.mood=true：发射 mod_set_mood(true)，不发射 mod_hide_mood
        story = make_story(
            [
                {"id": "n1", "type": "show", "character": "player", "position": "M"},
                {"id": "n2", "type": "say", "mode": "narrative", "text": "台词"},
                {"id": "nend", "type": "end"},
            ]
        )
        story["mood"] = True
        lua = compile_story(story)
        self.assertNotIn("mod_hide_mood", lua)
        self.assertIn("mod_set_mood(true)", lua)
        self.assertNotIn("mod_set_mood(false)", lua)

    def test_death(self):
        # 死亡文本节点：黑屏 + 居中旁白（已读 key）+ 场景跳转；自带收尾不加流转行
        lua = compile_story(
            make_story(
                [
                    {"id": "n1", "type": "music", "name": "普通_001"},
                    {
                        "id": "n2",
                        "type": "death",
                        "text": "你坠入山崖，万事休矣。",
                        "next": "Title",
                    },
                ]
            )
        )
        self.assertIn('\trunblock(flowcharts.view, "out")', lua)
        self.assertIn('\tgetvar(flowcharts.view, "ViewName").value = "black"', lua)
        self.assertIn('\trunblock(flowcharts.view, "view")', lua)
        self.assertIn("\tsetsaydialog(saydialogs.center)", lua)
        self.assertIn("\tsayoptions.waitforinput = true", lua)
        self.assertIn("\tsayoptions.fadewhendone  = true", lua)
        self.assertIn("\tsetcharacter(narrative)", lua)
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_MOD_main_n2"))', lua)
        self.assertIn('\tluamanager.ChangeScene("Title", "", "")', lua)
        # death 自带流转，不追加 return（ChangeScene 后直接收束函数）
        self.assertNotIn('ChangeScene("Title", "", "")\n\treturn', lua)

    def test_death_default_next_title(self):
        lua = self.lua_of({"id": "n1", "type": "death", "text": "命数已尽。"})
        self.assertIn('\tluamanager.ChangeScene("Title", "", "")', lua)

    def test_death_free_next(self):
        lua = self.lua_of(
            {"id": "n1", "type": "death", "text": "命数已尽。", "next": "Free"}
        )
        self.assertIn('\tluamanager.ChangeScene("Free", "", "")', lua)

    def test_choice(self):
        # choice 的 goto 目标必须存在，补一个目标节点 na
        lua = compile_story(
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "choice",
                        "options": [
                            {"text": "选项一", "goto": "na"},
                            {"text": "选项二", "goto": "nend"},
                            {"text": "选项三", "goto": "na"},
                        ],
                    },
                    {"id": "na", "type": "focus", "character": "player"},
                    {"id": "nend", "type": "end"},
                ]
            )
        )
        self.assertIn("\tsetmenudialog(menudialogs.Options)", lua)
        self.assertIn("\tlocal option1 = {}", lua)
        self.assertIn('\toption1[1] = "选项一"', lua)
        self.assertIn('\toption1[3] = "选项三"', lua)
        self.assertIn("\tlocal choice1 = choose(option1)", lua)
        self.assertIn("\tmenudialogs.Options.SetActive(false)", lua)
        self.assertIn("\tif choice1 == 1 then\n\t\treturn node_na()", lua)
        self.assertIn("\telseif choice1 == 2 then\n\t\treturn node_nend()", lua)

    def test_shock(self):
        lua = self.lua_of({"id": "n1", "type": "shock", "character": "brother4"})
        self.assertIn(
            '\tgetvar(flowcharts.common, "ShockPosition").value = '
            'characters.Get("brother4").State.holder.gameObject',
            lua,
        )
        self.assertIn('\tgetvar(flowcharts.common, "ShockDuration").value = 0.5', lua)
        self.assertIn('\trunblock(flowcharts.common, "shock")', lua)

    def test_mask(self):
        self.assertIn(
            "\tos_mask.Show(true)",
            self.lua_of({"id": "n1", "type": "mask", "show": True}),
        )
        self.assertIn(
            "\tos_mask.Show(false)",
            self.lua_of({"id": "n1", "type": "mask", "show": False}),
        )

    def test_intro(self):
        lua = self.lua_of({"id": "n1", "type": "intro", "character": "brother4"})
        self.assertIn('\trunwait(intropanel.Show("brother4"))', lua)

    def test_stat(self):
        lua = self.lua_of({"id": "n1", "type": "stat", "key": "mental", "delta": -5})
        self.assertIn('\tstatmodifymanager.Player("mental", -5, "", 1)', lua)
        self.assertIn('\twait(statmodifymanager.GetDisplayTime("mental"))', lua)

    def test_stat_no_wait(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "stat",
                "key": "money",
                "delta": 100,
                "waitDisplay": False,
            }
        )
        self.assertIn('\tstatmodifymanager.Player("money", 100, "", 1)', lua)
        self.assertNotIn("GetDisplayTime", lua)

    def test_affinity(self):
        lua = self.lua_of(
            {"id": "n1", "type": "affinity", "character": "brother4", "delta": 1}
        )
        self.assertIn('\tstatmodifymanager.Character("brother4", 1, 1)', lua)

    def test_flag(self):
        # 契约 §4：写游戏经历 + 设置 mod 内状态，两行
        lua = self.lua_of({"id": "n1", "type": "flag", "flag": "DEMO_FLAG"})
        self.assertIn('\tstatmodifymanager.AddStory("DEMO_FLAG")', lua)
        self.assertIn('\tmodflags["DEMO_FLAG"] = true', lua)
        self.assertLess(
            lua.index('statmodifymanager.AddStory("DEMO_FLAG")'),
            lua.index('modflags["DEMO_FLAG"] = true'),
        )

    def test_branch_mod_two_cases(self):
        # source 默认 "mod"：value 1=已设置(then)，2=未设置(else)
        lua = compile_story(
            make_story(
                [
                    {"id": "n1", "type": "flag", "flag": "MY_FLAG"},
                    {
                        "id": "n2",
                        "type": "branch",
                        "flag": "MY_FLAG",
                        "cases": [
                            {"value": 1, "goto": "na"},
                            {"value": 2, "goto": "nend"},
                        ],
                    },
                    {"id": "na", "type": "focus", "character": "player"},
                    {"id": "nend", "type": "end"},
                ],
                start="n1",
            )
        )
        self.assertIn(
            '\tif modflags["MY_FLAG"] then\n\t\treturn node_na()\n'
            "\telse\n\t\treturn node_nend()\n\tend",
            lua,
        )
        self.assertNotIn("checkpointmanager", lua)

    def test_branch_mod_single_case_fallback(self):
        # 单 case：另一路落顺序下一节点（else 兜底）
        lua = compile_story(
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "branch",
                        "flag": "MY_FLAG",
                        "cases": [{"value": 1, "goto": "na"}],
                    },
                    {"id": "n2", "type": "focus", "character": "player"},
                    {"id": "na", "type": "focus", "character": "brother4"},
                    {"id": "nend", "type": "end"},
                ],
                start="n1",
            )
        )
        self.assertIn(
            '\tif modflags["MY_FLAG"] then\n\t\treturn node_na()\n'
            "\telse\n\t\treturn node_n2()\n\tend",
            lua,
        )
        # 反过来只有 value=2 的 case：已设置一路落顺序下一节点
        lua2 = compile_story(
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "branch",
                        "flag": "MY_FLAG",
                        "cases": [{"value": 2, "goto": "na"}],
                    },
                    {"id": "n2", "type": "focus", "character": "player"},
                    {"id": "na", "type": "focus", "character": "brother4"},
                    {"id": "nend", "type": "end"},
                ],
                start="n1",
            )
        )
        self.assertIn(
            '\tif modflags["MY_FLAG"] then\n\t\treturn node_n2()\n'
            "\telse\n\t\treturn node_na()\n\tend",
            lua2,
        )

    def test_branch_game(self):
        # source="game"：checkpointmanager.Switch + else 兜底落顺序下一节点
        lua = compile_story(
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "branch",
                        "source": "game",
                        "flag": "S0003_01_001",
                        "cases": [
                            {"value": 1, "goto": "na"},
                            {"value": 2, "goto": "nend"},
                        ],
                    },
                    {"id": "na", "type": "focus", "character": "player"},
                    {"id": "nend", "type": "end"},
                ]
            )
        )
        self.assertIn('\tlocal branch1 = checkpointmanager.Switch("S0003_01_001")', lua)
        self.assertIn("\tif branch1 == 1 then\n\t\treturn node_na()", lua)
        self.assertIn("\telseif branch1 == 2 then\n\t\treturn node_nend()", lua)
        # else 兜底：未命中任何 case（含查不到检查点返回 0）落顺序下一节点 na
        self.assertIn("\telse\n\t\treturn node_na()\n\tend", lua)

    def test_wait(self):
        lua = self.lua_of({"id": "n1", "type": "wait", "seconds": 2})
        self.assertIn("\twait(2)", lua)

    def test_end(self):
        # 无 next_script：官方标准收尾 ChangeScene("Free", "", "")，不 emit Init
        lua = compile_story(
            linear_story({"id": "n1", "type": "focus", "character": "p"})
        )
        self.assertIn('\tluamanager.ChangeScene("Free", "", "")', lua)
        self.assertNotIn("luamanager.Init()", lua)
        self.assertNotIn("SetNextScript", lua)

    def test_end_next_script_with_mod_prefix(self):
        # 有 next_script：SetNextScript + Init 链到同包脚本
        story = make_story(
            [{"id": "n1", "type": "end", "next_script": "part2"}], start="n1"
        )
        lua = compile_story(story, mod_info=MANIFEST)
        self.assertIn('\tluamanager.SetNextScript("MOD_testmod_part2")', lua)
        self.assertIn("\tluamanager.Init()", lua)
        self.assertNotIn("ChangeScene", lua)
        # 裸编译（无 mod 信息）时退化为原始脚本 id
        lua2 = compile_story(story)
        self.assertIn('\tluamanager.SetNextScript("part2")', lua2)
        self.assertIn("\tluamanager.Init()", lua2)


# ---------------------------------------------------------------------------
# 非法输入报错
# ---------------------------------------------------------------------------


class TestValidationErrors(unittest.TestCase):
    def test_unknown_node_type(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "explode"}),
            '未知节点类型 "explode"',
            "n1",
        )

    def test_missing_required_field(self):
        assert_compile_error(
            self,
            linear_story({"id": "n5", "type": "say", "character": "player"}),
            '缺少必填字段 "text"',
            "n5",
        )

    def test_goto_to_missing_node(self):
        assert_compile_error(
            self,
            linear_story(
                {"id": "n1", "type": "music", "name": "普通_001", "goto": "ghost"}
            ),
            'goto 指向不存在的节点 "ghost"',
            "n1",
        )

    def test_choice_option_goto_missing(self):
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "choice",
                    "options": [
                        {"text": "甲", "goto": "nend"},
                        {"text": "乙", "goto": "ghost"},
                    ],
                }
            ),
            'goto 指向不存在的节点 "ghost"',
        )

    def test_choice_dialog_restricted_to_options(self):
        # 其余皮肤是自由场景 break 格式菜单，纯文本选项会崩溃（BreakOptionButton）
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "choice",
                    "dialog": "Talk",
                    "options": [
                        {"text": "甲", "goto": "nend"},
                        {"text": "乙", "goto": "nend"},
                    ],
                }
            ),
            'dialog 只支持 "Options"',
            "BreakOptionButton",
        )
        # Options 正常通过
        validate_story(
            linear_story(
                {
                    "id": "n1",
                    "type": "choice",
                    "options": [
                        {"text": "甲", "goto": "nend"},
                        {"text": "乙", "goto": "nend"},
                    ],
                }
            )
        )

    def test_say_loads_character_portrait(self):
        # 表情差分：say/show 必须发射 LoadCharacterPortrait（官方 93% 用法实证），
        # 否则台上人物立绘不随表情切换，只有气泡变
        lua = compile_story(
            linear_story(
                {
                    "id": "n1",
                    "type": "say",
                    "character": "player",
                    "portrait": "nervous1",
                    "text": "对话",
                }
            )
        )
        self.assertIn('	characters.LoadCharacterPortrait("player", "nervous1")', lua)
        lua_show = compile_story(
            linear_story(
                {"id": "n1", "type": "show", "character": "player", "position": "M"}
            )
        )
        self.assertIn(
            '	characters.LoadCharacterPortrait("player", "normal")', lua_show
        )

    def test_choice_option_count(self):
        for options in (
            [{"text": "一", "goto": "nend"}],
            [{"text": str(i), "goto": "nend"} for i in range(5)],
        ):
            assert_compile_error(
                self,
                linear_story({"id": "n1", "type": "choice", "options": options}),
                "选项数必须在 2~4 之间",
                "n1",
            )

    def test_start_missing(self):
        story = make_story([{"id": "n1", "type": "end"}], start="ghost")
        assert_compile_error(self, story, 'start 指向不存在的节点 "ghost"')

    def test_duplicate_node_id(self):
        assert_compile_error(
            self,
            make_story(
                [
                    {"id": "n1", "type": "end"},
                    {"id": "n1", "type": "end"},
                ]
            ),
            '节点 id "n1" 重复',
        )

    def test_say_character_required_unless_narrative(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "say", "text": "hi"}),
            'mode="character" 时必填字段 "character"',
            "n1",
        )
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "say", "mode": "think", "text": "hi"}),
            '必填字段 "character"',
        )
        # narrative 可省略 character：应通过
        validate_story(
            linear_story({"id": "n1", "type": "say", "mode": "narrative", "text": "hi"})
        )

    def test_bad_field_type(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "wait", "seconds": "1.5"}),
            '字段 "seconds" 必须是数值',
            "n1",
        )

    def test_bool_not_number(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "stat", "key": "mental", "delta": True}),
            '字段 "delta" 必须是数值',
        )

    def test_unknown_field(self):
        assert_compile_error(
            self,
            linear_story(
                {"id": "n1", "type": "music", "name": "普通_001", "naem": "x"}
            ),
            '未知字段 "naem"',
            "n1",
        )

    def test_bad_facing_and_mode(self):
        assert_compile_error(
            self,
            linear_story(
                {"id": "n1", "type": "face", "character": "p", "facing": "up"}
            ),
            '字段 "facing"',
        )
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "say",
                    "character": "p",
                    "mode": "shout",
                    "text": "x",
                }
            ),
            '字段 "mode"',
        )

    def test_last_node_must_end(self):
        assert_compile_error(
            self,
            make_story(
                [
                    {"id": "n1", "type": "end"},
                    {"id": "n2", "type": "focus", "character": "player"},
                ]
            ),
            "最后一个节点且没有显式 goto",
            "n2",
        )

    def test_goto_forbidden_on_choice_branch_end(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "end", "goto": "nend"}),
            '不允许显式 "goto"',
            "n1",
        )

    def test_branch_rules(self):
        # cases 为空
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "branch", "flag": "F", "cases": []}),
            "至少需要 1 个分支",
        )
        # case value 重复
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "branch",
                    "flag": "F",
                    "cases": [
                        {"value": 1, "goto": "nend"},
                        {"value": 1, "goto": "nend"},
                    ],
                }
            ),
            "重复",
        )
        # source="mod"（默认）时 value 只能 1/2
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "branch",
                    "flag": "F",
                    "cases": [{"value": 3, "goto": "nend"}],
                }
            ),
            'source="mod" 时 value 只能是 1',
            "n1",
        )
        # source="game" 时 value 可为任意整数（官方检查点返回值）
        validate_story(
            linear_story(
                {
                    "id": "n1",
                    "type": "branch",
                    "source": "game",
                    "flag": "S0003_01_001",
                    "cases": [{"value": 7, "goto": "nend"}],
                }
            )
        )
        # 非法 source 值
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "branch",
                    "source": "save",
                    "flag": "F",
                    "cases": [{"value": 1, "goto": "nend"}],
                }
            ),
            '字段 "source"',
        )

    def test_branch_last_node_uncovered(self):
        # mod 单 case 作最后节点：另一路 else 无落点 → 报错
        assert_compile_error(
            self,
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "branch",
                        "flag": "F",
                        "cases": [{"value": 1, "goto": "n2"}],
                    },
                    {"id": "n2", "type": "end"},
                    {
                        "id": "n3",
                        "type": "branch",
                        "flag": "F",
                        "cases": [{"value": 2, "goto": "n2"}],
                    },
                ]
            ),
            "else 没有落点",
            "n3",
        )
        # game 模式作最后节点：Switch 可返回任意值，永远有未覆盖 → 报错
        assert_compile_error(
            self,
            make_story(
                [
                    {"id": "n2", "type": "end"},
                    {
                        "id": "n1",
                        "type": "branch",
                        "source": "game",
                        "flag": "S0003_01_001",
                        "cases": [
                            {"value": 1, "goto": "n2"},
                            {"value": 2, "goto": "n2"},
                        ],
                    },
                ],
                start="n2",
            ),
            "else 没有落点",
            "n1",
        )
        # mod 双 case（1+2 全覆盖）作最后节点：合法
        validate_story(
            make_story(
                [
                    {"id": "n2", "type": "end"},
                    {
                        "id": "n1",
                        "type": "branch",
                        "flag": "F",
                        "cases": [
                            {"value": 1, "goto": "n2"},
                            {"value": 2, "goto": "n2"},
                        ],
                    },
                ],
                start="n1",
            )
        )

    def test_bad_node_id_charset(self):
        assert_compile_error(
            self,
            linear_story({"id": "n-1", "type": "focus", "character": "p"}),
            "节点 id 必须是 [a-zA-Z0-9_]+",
        )

    def test_manifest_errors(self):
        with self.assertRaises(LomcError) as cm:
            validate_manifest({"format": 2, "id": "x"})
        self.assertIn('"format" 必须固定为 1', str(cm.exception))
        bad = dict(MANIFEST)
        del bad["author"]
        with self.assertRaises(LomcError) as cm:
            validate_manifest(bad)
        self.assertIn('缺少必填字段 "author"', str(cm.exception))
        bad2 = dict(MANIFEST, id="TestMod")
        with self.assertRaises(LomcError) as cm:
            validate_manifest(bad2)
        self.assertIn('"id"', str(cm.exception))


# ---------------------------------------------------------------------------
# pack 打包 + 解压往返
# ---------------------------------------------------------------------------


class TestPack(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.mod_dir = os.path.join(self.tmp.name, "testmod")
        os.makedirs(os.path.join(self.mod_dir, "story"))
        with open(
            os.path.join(self.mod_dir, "manifest.json"), "w", encoding="utf-8"
        ) as f:
            json.dump(MANIFEST, f, ensure_ascii=False, indent=2)

    def tearDown(self):
        self.tmp.cleanup()

    def write_story(self, story, name=None):
        name = name or story["id"]
        path = os.path.join(self.mod_dir, "story", name + ".json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(story, f, ensure_ascii=False, indent=2)
        return path

    def test_pack_roundtrip(self):
        main = make_story(
            [
                {"id": "n1", "type": "music", "name": "普通_001"},
                {
                    "id": "n2",
                    "type": "say",
                    "mode": "narrative",
                    "text": "打包对话文本",
                },
                {"id": "n3", "type": "end", "next_script": "extra"},
            ]
        )
        extra = make_story(
            [{"id": "x1", "type": "death", "text": "死亡文本演示", "next": "Title"}],
            story_id="extra",
            start="x1",
        )
        self.write_story(main)
        self.write_story(extra)

        out = pack_mod(self.mod_dir)
        # 默认输出：<mod目录> 同级 <目录名>.lommod
        self.assertEqual(out, os.path.join(self.tmp.name, "testmod.lommod"))
        self.assertTrue(zipfile.is_zipfile(out))

        with zipfile.ZipFile(out) as zf:
            names = set(zf.namelist())
            self.assertEqual(
                names,
                {
                    "manifest.json",
                    "story/main.json",
                    "story/extra.json",
                    "lua/main.lua",
                    "lua/extra.lua",
                    "texts.json",
                },
            )
            manifest_back = json.loads(zf.read("manifest.json").decode("utf-8"))
            self.assertEqual(manifest_back, MANIFEST)
            story_back = json.loads(zf.read("story/main.json").decode("utf-8"))
            self.assertEqual(story_back, main)
            lua_main = zf.read("lua/main.lua").decode("utf-8")
            lua_extra = zf.read("lua/extra.lua").decode("utf-8")
            # 已读文本表（契约 §1）：say/death 节点的 key → 文本
            texts = json.loads(zf.read("texts.json").decode("utf-8"))
            self.assertEqual(
                texts,
                {
                    "MOD_testmod_main_n2": "打包对话文本",
                    "MOD_testmod_extra_x1": "死亡文本演示",
                },
            )

        # 包内 lua 与直接编译结果一致
        self.assertEqual(
            lua_main, compile_story(main, mod_info=MANIFEST, source="story/main.json")
        )
        self.assertIn('luamanager.SetNextScript("MOD_testmod_extra")', lua_main)
        self.assertIn('luamanager.GetStoryText("MOD_testmod_main_n2")', lua_main)
        self.assertIn("return node_n1()", lua_main)
        self.assertIn("return node_x1()", lua_extra)
        # extra 的 death 自带场景跳转收尾（key 走已读机制）
        self.assertIn('luamanager.GetStoryText("MOD_testmod_extra_x1")', lua_extra)
        self.assertIn('luamanager.ChangeScene("Title", "", "")', lua_extra)
        self.assertNotIn("luamanager.Init()", lua_extra)

    def test_pack_missing_manifest(self):
        os.remove(os.path.join(self.mod_dir, "manifest.json"))
        with self.assertRaises(LomcError) as cm:
            pack_mod(self.mod_dir)
        self.assertIn("缺少 manifest.json", str(cm.exception))

    def test_pack_entry_missing(self):
        self.write_story(
            make_story([{"id": "n1", "type": "end"}], story_id="other", start="n1")
        )
        with self.assertRaises(LomcError) as cm:
            pack_mod(self.mod_dir)
        self.assertIn('entry 指向的入口脚本 "main" 不存在', str(cm.exception))

    def test_pack_next_script_missing(self):
        self.write_story(
            make_story(
                [{"id": "n1", "type": "end", "next_script": "ghost"}], start="n1"
            )
        )
        with self.assertRaises(LomcError) as cm:
            pack_mod(self.mod_dir)
        self.assertIn('next_script 指向包内不存在的脚本 "ghost"', str(cm.exception))
        self.assertIn('节点 "n1"', str(cm.exception))

    def test_pack_filename_id_mismatch(self):
        self.write_story(
            make_story([{"id": "n1", "type": "end"}], start="n1"), name="zzz"
        )
        with self.assertRaises(LomcError) as cm:
            pack_mod(self.mod_dir)
        self.assertIn("文件名与内部 id 不一致", str(cm.exception))

    def test_pack_invalid_story_aborts(self):
        self.write_story(
            make_story([{"id": "n1", "type": "explode"}, {"id": "n2", "type": "end"}])
        )
        with self.assertRaises(LomcError) as cm:
            pack_mod(self.mod_dir)
        self.assertIn('未知节点类型 "explode"', str(cm.exception))
        # 失败的 pack 不应留下产物
        self.assertFalse(os.path.exists(os.path.join(self.tmp.name, "testmod.lommod")))


# ---------------------------------------------------------------------------
# CLI 冒烟测试（子进程跑 python -m lomc）
# ---------------------------------------------------------------------------


class TestCli(unittest.TestCase):
    def run_cli(self, *argv):
        # Windows 控制台默认 GBK，子进程输出中文会乱码/解码失败，
        # 统一用 PYTHONIOENCODING 强制 UTF-8
        env = dict(os.environ, PYTHONIOENCODING="utf-8")
        return subprocess.run(
            [sys.executable, "-m", "lomc"] + list(argv),
            cwd=COMPILER_ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            env=env,
        )

    def test_check_ok_and_fail(self):
        with tempfile.TemporaryDirectory() as tmp:
            good = os.path.join(tmp, "good.json")
            with open(good, "w", encoding="utf-8") as f:
                json.dump(
                    linear_story({"id": "n1", "type": "music", "name": "普通_001"}), f
                )
            r = self.run_cli("check", good)
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertIn("校验通过", r.stdout)

            bad = os.path.join(tmp, "bad.json")
            with open(bad, "w", encoding="utf-8") as f:
                json.dump(
                    make_story(
                        [{"id": "n1", "type": "wat"}, {"id": "n2", "type": "end"}]
                    ),
                    f,
                )
            r = self.run_cli("check", bad)
            self.assertEqual(r.returncode, 1)
            self.assertIn("错误", r.stderr)
            self.assertIn("未知节点类型", r.stderr)

    def test_build_and_pack(self):
        with tempfile.TemporaryDirectory() as tmp:
            story_path = os.path.join(tmp, "main.json")
            with open(story_path, "w", encoding="utf-8") as f:
                json.dump(linear_story({"id": "n1", "type": "wait", "seconds": 1}), f)
            out_lua = os.path.join(tmp, "out.lua")
            r = self.run_cli("build", story_path, "-o", out_lua)
            self.assertEqual(r.returncode, 0, r.stderr)
            with open(out_lua, encoding="utf-8") as f:
                self.assertIn("return node_n1()", f.read())

            mod_dir = os.path.join(tmp, "mymod")
            os.makedirs(os.path.join(mod_dir, "story"))
            with open(
                os.path.join(mod_dir, "manifest.json"), "w", encoding="utf-8"
            ) as f:
                json.dump(MANIFEST, f)
            os.replace(story_path, os.path.join(mod_dir, "story", "main.json"))
            out_pkg = os.path.join(tmp, "mymod.lommod")
            r = self.run_cli("pack", mod_dir, "-o", out_pkg)
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertTrue(zipfile.is_zipfile(out_pkg))


# ---------------------------------------------------------------------------
# v3 新增节点 codegen（逐条对照契约 §3.1/§4）
# ---------------------------------------------------------------------------


class TestNewNodeCodegen(unittest.TestCase):
    def lua_of(self, node, *extra_nodes, start=None):
        nodes = [node] + list(extra_nodes) + [{"id": "nend", "type": "end"}]
        return compile_story(make_story(nodes, start=start))

    def test_music_ops(self):
        self.assertIn(
            '\tluamanager.PlayMusic("普通_001")',
            self.lua_of({"id": "n1", "type": "music", "name": "普通_001"}),
        )
        self.assertIn(
            "\tluamanager.StopMusic()",
            self.lua_of({"id": "n1", "type": "music", "name": "x", "op": "stop"}),
        )
        self.assertIn(
            "\tluamanager.FadeOutMusic(2)",
            self.lua_of({"id": "n1", "type": "music", "name": "x", "op": "fadeout"}),
        )
        self.assertIn(
            "\tluamanager.FadeOutMusic(3.5)",
            self.lua_of(
                {
                    "id": "n1",
                    "type": "music",
                    "name": "x",
                    "op": "fadeout",
                    "seconds": 3.5,
                }
            ),
        )

    def test_sound(self):
        self.assertIn(
            '\tluamanager.PlaySound("揍人_001")',
            self.lua_of({"id": "n1", "type": "sound", "name": "揍人_001"}),
        )
        self.assertIn(
            '\tluamanager.PlayEnvSound("雨天_001")',
            self.lua_of(
                {"id": "n1", "type": "sound", "name": "雨天_001", "kind": "env"}
            ),
        )
        self.assertIn(
            "\tluamanager.FadeOutEnvSound(1)",
            self.lua_of(
                {
                    "id": "n1",
                    "type": "sound",
                    "name": "x",
                    "kind": "env",
                    "op": "fadeout",
                }
            ),
        )

    def test_offset(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "offset",
                "character": "girl1",
                "x": 100,
                "y": 0,
                "duration": 0.5,
            }
        )
        self.assertIn(
            '\trunwait(characters.MoveOffsetCoroutine("girl1", 100, 0, 0.5))', lua
        )

    def test_effect(self):
        lua = self.lua_of(
            {"id": "n1", "type": "effect", "name": "Hit_001", "x": 10, "y": -5}
        )
        self.assertIn('\teffects.SetupEffect("Hit_001", 10, -5, 1, 1, 1, 1)', lua)

    def test_transition(self):
        self.assertIn(
            '\trunwait(transitionblack.TransitionIn("lr"))',
            self.lua_of({"id": "n1", "type": "transition", "phase": "in"}),
        )
        self.assertIn(
            '\trunwait(transitionblack.TransitionOut("bt"))',
            self.lua_of(
                {"id": "n1", "type": "transition", "phase": "out", "dir": "bt"}
            ),
        )

    def test_camera(self):
        self.assertIn(
            '\tmaincamera.ActiveVolume("stage-memory", 1)',
            self.lua_of(
                {"id": "n1", "type": "camera", "name": "stage-memory", "active": True}
            ),
        )
        self.assertIn(
            '\tmaincamera.ActiveVolume("stage-memory", 0)',
            self.lua_of(
                {"id": "n1", "type": "camera", "name": "stage-memory", "active": False}
            ),
        )

    def test_block(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "block",
                "flowchart": "common",
                "name": "flash",
                "vars": [{"name": "FlashDuration", "value": 0.1}],
            }
        )
        self.assertIn('\tgetvar(flowcharts.common, "FlashDuration").value = 0.1', lua)
        self.assertIn('\trunblock(flowcharts.common, "flash")', lua)
        # 无 vars：直接 runblock
        lua2 = self.lua_of(
            {"id": "n1", "type": "block", "flowchart": "view", "name": "out_white"}
        )
        self.assertIn('\trunblock(flowcharts.view, "out_white")', lua2)
        self.assertNotIn("getvar", lua2)

    def test_cg(self):
        self.assertIn(
            '\trunwait(mainui.ShowPicture("forge_work_001"))',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "cg",
                    "action": "show",
                    "kind": "picture",
                    "key": "forge_work_001",
                }
            ),
        )
        self.assertIn(
            "\trunwait(mainui.HidePicture())",
            self.lua_of(
                {"id": "n1", "type": "cg", "action": "hide", "kind": "picture"}
            ),
        )
        self.assertIn(
            '\trunwait(mainui.ShowMap("Home", "A1"))',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "cg",
                    "action": "show",
                    "kind": "map",
                    "key": "Home",
                    "key2": "A1",
                }
            ),
        )
        self.assertIn(
            '\trunwait(mainui.ShowFamilyTree("A_10", "A_11", 3, 2))',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "cg",
                    "action": "show",
                    "kind": "family",
                    "key": "A_10",
                    "key2": "A_11",
                    "n1": 3,
                    "n2": 2,
                }
            ),
        )
        # 官方 DisplayTitle 无 runwait
        self.assertIn(
            '\tmainui.DisplayTitle("練武場")',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "cg",
                    "action": "show",
                    "kind": "title",
                    "key": "練武場",
                }
            ),
        )

    def test_stat_mode_display(self):
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "stat",
                "key": "mental",
                "delta": -5,
                "mode": "m",
                "display": 0,
                "waitDisplay": False,
            }
        )
        self.assertIn('\tstatmodifymanager.Player("mental", -5, "m", 0)', lua)
        self.assertNotIn("GetDisplayTime", lua)

    def test_stat_set(self):
        self.assertIn(
            '\tstatmodifymanager.SetPlayer("money", 0)',
            self.lua_of({"id": "n1", "type": "stat_set", "key": "money", "value": 0}),
        )
        self.assertIn(
            '\tstatmodifymanager.UpdateSetPlayerStat("title", 10)',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "stat_set",
                    "key": "title",
                    "value": 10,
                    "update": True,
                }
            ),
        )

    def test_talent(self):
        self.assertIn(
            '\tstatmodifymanager.AddTalent("3004", 1)',
            self.lua_of({"id": "n1", "type": "talent", "talent": "3004", "level": 1}),
        )
        self.assertIn(
            '\tstatmodifymanager.AddTalent("9105", -1)',
            self.lua_of({"id": "n1", "type": "talent", "talent": "9105", "level": -1}),
        )

    def test_item(self):
        self.assertIn(
            '\tstatmodifymanager.AddBook("6002", 1)',
            self.lua_of({"id": "n1", "type": "item", "kind": "book", "item": "6002"}),
        )
        self.assertIn(
            '\tstatmodifymanager.AddMisc("2001", 50)',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "item",
                    "kind": "misc",
                    "item": "2001",
                    "count": 50,
                }
            ),
        )
        self.assertIn(
            '\tstatmodifymanager.AddSpecial("4005", 1)',
            self.lua_of(
                {"id": "n1", "type": "item", "kind": "special", "item": "4005"}
            ),
        )
        self.assertIn(
            '\tstatmodifymanager.RemoveMisc("5002")',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "item",
                    "kind": "misc",
                    "item": "5002",
                    "remove": True,
                }
            ),
        )

    def test_game_flag(self):
        self.assertIn(
            '\tstatmodifymanager.SetFlag("M0001_00", 1)',
            self.lua_of(
                {"id": "n1", "type": "game_flag", "flag": "M0001_00", "value": 1}
            ),
        )
        self.assertIn(
            '\tstatmodifymanager.AddFlag("H00001", -1)',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "game_flag",
                    "flag": "H00001",
                    "value": -1,
                    "op": "add",
                }
            ),
        )

    def test_enemy(self):
        self.assertIn(
            '\tstatmodifymanager.ModifyEnemyTeam("400", -10, 1)',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "enemy",
                    "op": "team",
                    "enemy": "400",
                    "value": -10,
                }
            ),
        )
        self.assertIn(
            '\tstatmodifymanager.ModifyEnemyId("001")',
            self.lua_of({"id": "n1", "type": "enemy", "op": "id", "enemy": "001"}),
        )

    def test_battle_skill(self):
        self.assertIn(
            '\tluamanager.SetPlayerBattleSkill("special3", 2)',
            self.lua_of(
                {"id": "n1", "type": "battle_skill", "op": "set", "key": "special3"}
            ),
        )
        self.assertIn(
            '\tluamanager.SetBattleSkillActive("special3", 1)',
            self.lua_of(
                {"id": "n1", "type": "battle_skill", "op": "active", "key": "special3"}
            ),
        )
        self.assertIn(
            "\tluamanager.ResetBattleSkill()",
            self.lua_of({"id": "n1", "type": "battle_skill", "op": "reset"}),
        )

    def test_mission(self):
        self.assertIn(
            '\tstatmodifymanager.Mission("Main", "M0001")',
            self.lua_of(
                {"id": "n1", "type": "mission", "name": "Main", "key": "M0001"}
            ),
        )

    def test_time(self):
        self.assertIn(
            "\tluamanager.SetGameTime(1, 4, 1)",
            self.lua_of(
                {
                    "id": "n1",
                    "type": "time",
                    "op": "set",
                    "year": 1,
                    "month": 4,
                    "stage": 1,
                }
            ),
        )
        self.assertIn(
            "\tluamanager.NextRound()",
            self.lua_of({"id": "n1", "type": "time", "op": "round"}),
        )
        self.assertIn(
            "\tluamanager.NextMonth()",
            self.lua_of({"id": "n1", "type": "time", "op": "month"}),
        )
        self.assertIn(
            '\tluamanager.SetMissionTime("S0106_01", 0, 0, 1)',
            self.lua_of(
                {
                    "id": "n1",
                    "type": "time",
                    "op": "mission",
                    "name": "S0106_01",
                    "year": 0,
                    "month": 0,
                    "stage": 1,
                }
            ),
        )

    def test_autosave(self):
        self.assertIn(
            "\tluamanager.AutoSave()",
            self.lua_of({"id": "n1", "type": "autosave"}),
        )
        self.assertIn(
            "\tluamanager.AutoFreeSave()",
            self.lua_of({"id": "n1", "type": "autosave", "kind": "free"}),
        )
        self.assertIn(
            "\tluamanager.PrologueSave(0)",
            self.lua_of({"id": "n1", "type": "autosave", "kind": "prologue"}),
        )
        lua = self.lua_of(
            {"id": "n1", "type": "autosave", "kind": "story", "save_button": 1}
        )
        self.assertIn("\tluamanager.AutoSave()", lua)
        self.assertIn("\tluamanager.ToggleSaveButton(1)", lua)

    def test_dice(self):
        # S0205_01_001：官方 2 结果带、骰子范围 99（S0205_01 故事脚本实证）
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "dice",
                "check": "S0205_01_001",
                "options": [
                    {
                        "goto_大成功": "",  # 2 带无独立大成功档，允许空
                        "goto_成功": "nb",
                        "goto_失败": "na",
                    }
                ],
            },
            {"id": "na", "type": "focus", "character": "player"},
            {"id": "nb", "type": "focus", "character": "brother4"},
        )
        self.assertIn("\tsetmenudialog(menudialogs.Dice)", lua)
        self.assertIn("\tlocal dice_rand1 = math.random(99)", lua)
        self.assertIn("\tdicemenudialog.SetRandom(99, dice_rand1)", lua)
        self.assertIn(
            '\tlocal dice_result1 = checkpointmanager.Dice("S0205_01_001", dice_rand1)',
            lua,
        )
        self.assertIn("\tlocal dice_opts1 = {}", lua)
        # 官方结果带（差→好）：文本+条件逐带发射
        self.assertIn('\tdice_opts1[1] = "O_S0205_01_001|<40"', lua)
        self.assertIn('\tdice_opts1[2] = "O_S0205_01_002|>=40"', lua)
        self.assertIn(
            '\trunwait(dicemenudialog.ExecuteRoll(dice_opts1, 1, "S0205_01_001"))',
            lua,
        )
        self.assertIn("\tlocal dice_sel1 = dicemenudialog.ResultSelection", lua)
        # 2 带分支：1→失败，else→成功（最优带）
        self.assertIn("\tif dice_sel1 == 1 then\n\t\treturn node_na()", lua)
        self.assertIn("\telse\n\t\treturn node_nb()\n\tend", lua)
        self.assertNotIn("elseif dice_sel1 == 2", lua)

    def test_dice_three_bands(self):
        # Ch_6_8_2_Break_01_001：官方 3 结果带、骰子范围 60（ch6_8_2_break_start_01 实证）
        lua = self.lua_of(
            {
                "id": "n1",
                "type": "dice",
                "check": "Ch_6_8_2_Break_01_001",
                "options": [
                    {
                        "goto_大成功": "na",
                        "goto_成功": "nb",
                        "goto_失败": "nc",
                    }
                ],
            },
            {"id": "na", "type": "focus", "character": "player"},
            {"id": "nb", "type": "focus", "character": "brother4"},
            {"id": "nc", "type": "focus", "character": "brother4"},
        )
        self.assertIn("\tlocal dice_rand1 = math.random(60)", lua)
        self.assertIn('\tdice_opts1[1] = "O_6_8_2_Break_01_002|<20"', lua)
        self.assertIn('\tdice_opts1[2] = "O_6_8_2_Break_01_003|<80"', lua)
        self.assertIn('\tdice_opts1[3] = "O_6_8_2_Break_01_004|>=80"', lua)
        # 3 带分支：1→失败，2→成功，末带→大成功
        self.assertIn("\tif dice_sel1 == 1 then\n\t\treturn node_nc()", lua)
        self.assertIn("\telseif dice_sel1 == 2 then\n\t\treturn node_nb()", lua)
        self.assertIn("\telse\n\t\treturn node_na()\n\tend", lua)

    def test_dice_inverted_bands(self):
        # 倒序检查点（官方展示顺序 [">80",">40","<=40"]）：
        # 带 1 是最优带 -> selection 1 应走 goto_大成功
        import lomc.dice_data as dd

        saved = dd._META
        try:
            dd._META = {
                "Test_Inv": {
                    "max": 99,
                    "bands": [
                        {"text": "A", "cond": ">80"},
                        {"text": "B", "cond": ">40"},
                        {"text": "C", "cond": "<=40"},
                    ],
                }
            }
            lua = compile_story(
                linear_story(
                    {
                        "id": "n1",
                        "type": "dice",
                        "check": "Test_Inv",
                        "options": [
                            {"goto_大成功": "na", "goto_成功": "nb", "goto_失败": "nc"}
                        ],
                    },
                    {"id": "na", "type": "focus", "character": "player"},
                    {"id": "nb", "type": "focus", "character": "brother4"},
                    {"id": "nc", "type": "focus", "character": "trainee1"},
                )
            )
            # 选项仍按展示顺序发射
            self.assertIn('dice_opts1[1] = "A|>80"', lua)
            self.assertIn('dice_opts1[3] = "C|<=40"', lua)
            # 分支按质量：selection 1（>80 最优）→ 大成功；2（>40）→ 成功；3（<=40）→ 失败
            tab, nl = chr(9), chr(10)
            self.assertIn(
                tab + "if dice_sel1 == 1 then" + nl + tab * 2 + "return node_na()", lua
            )
            self.assertIn(
                tab + "elseif dice_sel1 == 2 then" + nl + tab * 2 + "return node_nb()",
                lua,
            )
            self.assertIn(
                tab + "else" + nl + tab * 2 + "return node_nc()" + nl + tab + "end", lua
            )
        finally:
            dd._META = saved

    def test_goto_scene(self):
        lua = self.lua_of(
            {"id": "n1", "type": "goto_scene", "scene": "Combat", "key": "5102_01"}
        )
        self.assertIn('\tluamanager.ChangeScene("Combat", "5102_01", "Story")', lua)
        # 默认 key="" / next="Story"
        lua2 = self.lua_of({"id": "n1", "type": "goto_scene", "scene": "Title"})
        self.assertIn('\tluamanager.ChangeScene("Title", "", "Story")', lua2)
        # goto_scene 自带跳转，不追加流转行
        self.assertNotIn("return node_nend()", lua2)

    def test_panel(self):
        self.assertIn(
            "\trunwait(martialpanel.Open(0))",
            self.lua_of({"id": "n1", "type": "panel", "panel": "martial"}),
        )
        self.assertIn(
            "\trunwait(shoppanel.Open(10))",
            self.lua_of({"id": "n1", "type": "panel", "panel": "shop", "discount": 10}),
        )
        # newshop 不 runwait
        lua = self.lua_of({"id": "n1", "type": "panel", "panel": "newshop"})
        self.assertIn("\tshoppanel.NewShop()", lua)
        self.assertNotIn("runwait(shoppanel.NewShop", lua)
        self.assertIn(
            '\trunwait(endgamepanel.Open("20003"))',
            self.lua_of(
                {"id": "n1", "type": "panel", "panel": "endgame", "key": "20003"}
            ),
        )
        self.assertIn(
            '\trunwait(cgvideopanel.Open("hand_001", 0))',
            self.lua_of(
                {"id": "n1", "type": "panel", "panel": "cgvideo", "key": "hand_001"}
            ),
        )

    def test_raw(self):
        code = '-- 自定义逻辑\nluamanager.PlayMusic("普通_001")'
        lua = self.lua_of({"id": "n1", "type": "raw", "code": code})
        # 原样插入（不加缩进）+ 其后流转照常
        self.assertIn('\n-- 自定义逻辑\nluamanager.PlayMusic("普通_001")\n', lua)
        self.assertIn("\treturn node_nend()", lua)

    def test_say_center(self):
        lua = self.lua_of(
            {"id": "n1", "type": "say", "mode": "center", "text": "居中旁白"}
        )
        self.assertIn("\tsetsaydialog(saydialogs.center)", lua)
        self.assertIn("\tsetcharacter(narrative)", lua)
        self.assertIn('\tsay(luamanager.GetStoryText("MOD_MOD_main_n1"))', lua)
        self.assertNotIn("showPortrait", lua)

    def test_choice_dialog_skin(self):
        # 契约 v3.3：choice 皮肤只允许 Options（其余为自由场景 break 格式菜单）
        lua = compile_story(
            make_story(
                [
                    {
                        "id": "n1",
                        "type": "choice",
                        "options": [
                            {"text": "甲", "goto": "nend"},
                            {"text": "乙", "goto": "nend"},
                        ],
                    },
                    {"id": "nend", "type": "end"},
                ]
            )
        )
        self.assertIn("\tsetmenudialog(menudialogs.Options)", lua)
        self.assertIn("\tmenudialogs.Options.SetActive(false)", lua)

    def test_terminal_node_types(self):
        # goto_scene / raw / dice / death 可作最后一个节点收尾（契约 §4）
        for last in (
            {"id": "n2", "type": "goto_scene", "scene": "Free"},
            {"id": "n2", "type": "raw", "code": "luamanager.AutoSave()"},
            {
                "id": "n2",
                "type": "dice",
                "check": "S0205_01_001",
                "options": [
                    {
                        "goto_大成功": "",
                        "goto_成功": "n1",
                        "goto_失败": "n1",
                    }
                ],
            },
            {"id": "n2", "type": "death", "text": "山崖坠亡。", "next": "Title"},
        ):
            validate_story(
                make_story(
                    [
                        {"id": "n1", "type": "focus", "character": "p", "goto": "n2"},
                        last,
                    ],
                    start="n1",
                )
            )


class TestNewNodeValidationErrors(unittest.TestCase):
    def test_sound_fadeout_requires_env(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "sound", "name": "x", "op": "fadeout"}),
            'op="fadeout" 仅支持 kind="env"',
            "n1",
        )

    def test_cg_rules(self):
        # hide + title 无官方 API
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "cg", "action": "hide", "kind": "title"}),
            'action="hide" 不支持 kind="title"',
        )
        # show map 缺 key2
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "cg",
                    "action": "show",
                    "kind": "map",
                    "key": "Home",
                }
            ),
            '必填字段 "key2"',
            "n1",
        )

    def test_item_remove_special(self):
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "item",
                    "kind": "special",
                    "item": "4005",
                    "remove": True,
                }
            ),
            "remove 仅支持",
            "n1",
        )

    def test_enemy_value_required(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "enemy", "op": "team", "enemy": "400"}),
            '必填字段 "value"',
            "n1",
        )
        # op="id" 不需要 value：通过
        validate_story(
            linear_story({"id": "n1", "type": "enemy", "op": "id", "enemy": "001"})
        )

    def test_battle_skill_key_required(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "battle_skill", "op": "set"}),
            '必填字段 "key"',
        )

    def test_time_fields(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "time", "op": "set", "year": 1}),
            '必填字段 "month"',
        )
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "time",
                    "op": "mission",
                    "year": 0,
                    "month": 0,
                    "stage": 1,
                }
            ),
            '必填字段 "name"',
        )

    def test_panel_key_required(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "panel", "panel": "cg"}),
            '必填字段 "key"',
        )

    def test_death_rules(self):
        # text 必填非空
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "death"}),
            '缺少必填字段 "text"',
            "n1",
        )
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "death", "text": "   "}),
            '字段 "text" 不能为空',
            "n1",
        )
        # next 只能是 Free/Title
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "death", "text": "死", "next": "Story"}),
            '字段 "next"',
            "n1",
        )
        # death 自带场景跳转，不允许显式 goto
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "death", "text": "死", "goto": "nend"}),
            '不允许显式 "goto"',
            "n1",
        )
        # 合法：末位 death 可收尾（自带 ChangeScene）
        validate_story(
            make_story(
                [
                    {"id": "n1", "type": "focus", "character": "p"},
                    {"id": "n2", "type": "death", "text": "命数已尽。", "next": "Free"},
                ],
                start="n1",
            )
        )

    def test_story_mood_type(self):
        # story 顶层 mood 必须是 bool
        story = linear_story({"id": "n1", "type": "music", "name": "x"})
        story["mood"] = "yes"
        assert_compile_error(self, story, '字段 "mood" 必须是布尔值')
        story["mood"] = False
        validate_story(story)

    def test_talent_level(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "talent", "talent": "3004", "level": 2}),
            '字段 "level" 必须是1 或 -1',
        )

    def test_official_id_nonempty(self):
        # dice.check / game_flag.flag / branch.flag 只校验非空，不查表
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "game_flag", "flag": "", "value": 1}),
            '字段 "flag" 必须是非空字符串',
        )
        # 不在官方清单里的 id 也放行（编辑器侧管清单）
        validate_story(
            linear_story(
                {"id": "n1", "type": "game_flag", "flag": "CUSTOM_ID", "value": 1}
            )
        )

    def test_dice_options(self):
        # 选项数不是恰好 1 条（三向 goto 载体）
        for options in (
            [],
            [
                {"goto_大成功": "nend", "goto_成功": "nend", "goto_失败": "nend"}
                for _ in range(2)
            ],
        ):
            assert_compile_error(
                self,
                linear_story(
                    {
                        "id": "n1",
                        "type": "dice",
                        "check": "S0205_01_001",
                        "options": options,
                    }
                ),
                "选项数必须在 1~1 之间",
                "n1",
            )
        # 检查点缺少官方元数据 → 报错（游戏内骰子菜单会 NRE 崩溃）
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "dice",
                    "check": "NOT_A_REAL_CHECK",
                    "options": [
                        {
                            "goto_大成功": "nend",
                            "goto_成功": "nend",
                            "goto_失败": "nend",
                        }
                    ],
                }
            ),
            "缺少官方元数据",
        )
        # 2 带检查点：goto_成功 / goto_失败 必填，goto_大成功 可选
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "dice",
                    "check": "S0205_01_001",
                    "options": [
                        {"goto_大成功": "", "goto_成功": "", "goto_失败": "nend"}
                    ],
                }
            ),
            '必填字段 "goto_成功"',
        )
        # 3 带检查点：goto_大成功 必填
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "dice",
                    "check": "Ch_6_8_2_Break_01_001",
                    "options": [
                        {"goto_大成功": "", "goto_成功": "nend", "goto_失败": "nend"}
                    ],
                }
            ),
            '必填字段 "goto_大成功"',
        )
        # goto 指向不存在节点
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "dice",
                    "check": "S0205_01_001",
                    "options": [
                        {"goto_大成功": "", "goto_成功": "ghost", "goto_失败": "nend"}
                    ],
                }
            ),
            'goto 指向不存在的节点 "ghost"',
        )

    def test_raw_empty_code(self):
        assert_compile_error(
            self,
            linear_story({"id": "n1", "type": "raw", "code": "  \n "}),
            '"code" 不能为空',
        )

    def test_no_goto_types_v3(self):
        # dice / goto_scene 也禁止显式 goto（契约 §4）
        assert_compile_error(
            self,
            linear_story(
                {"id": "n1", "type": "goto_scene", "scene": "Free", "goto": "nend"}
            ),
            '不允许显式 "goto"',
            "n1",
        )
        assert_compile_error(
            self,
            linear_story(
                {
                    "id": "n1",
                    "type": "dice",
                    "check": "S0205_01_001",
                    "goto": "nend",
                    "options": [
                        {"goto_大成功": "", "goto_成功": "nend", "goto_失败": "nend"}
                    ],
                }
            ),
            '不允许显式 "goto"',
        )


class TestWarnings(unittest.TestCase):
    """非致命警告：transition 黑幕隐患（官方 TransitionIn/Out 必须成对）。"""

    def test_transition_in_out_pair_no_warning(self):
        story = make_story(
            [
                {"id": "n1", "type": "transition", "phase": "in", "dir": "lr"},
                {"id": "n2", "type": "transition", "phase": "out", "dir": "rl"},
                {"id": "nend", "type": "end"},
            ]
        )
        warns = []
        validate_story(story, warnings=warns)
        self.assertEqual(warns, [])

    def test_transition_pair_need_not_be_adjacent(self):
        story = make_story(
            [
                {"id": "n1", "type": "transition", "phase": "in", "dir": "lr"},
                {"id": "n2", "type": "say", "mode": "center", "text": "中间"},
                {"id": "n3", "type": "transition", "phase": "out", "dir": "rl"},
                {"id": "nend", "type": "end"},
            ]
        )
        warns = []
        validate_story(story, warnings=warns)
        self.assertEqual(warns, [])

    def test_transition_in_without_out_warning(self):
        story = make_story(
            [
                {"id": "n1", "type": "transition", "phase": "in", "dir": "lr"},
                {"id": "nend", "type": "end"},
            ]
        )
        warns = []
        validate_story(story, warnings=warns)
        self.assertEqual(len(warns), 1)
        self.assertIn('"n1"', warns[0])
        self.assertIn("phase=out", warns[0])

    def test_transition_out_before_in_warns_noop(self):
        # 反序配对（snack_case 黑屏事故实态）：out 无黑幕可撤（无效操作），
        # in 之后无 out 解除 → 各一条警告，共两条
        story = make_story(
            [
                {"id": "n1", "type": "transition", "phase": "out", "dir": "lr"},
                {"id": "n2", "type": "transition", "phase": "in", "dir": "rl"},
                {"id": "nend", "type": "end"},
            ]
        )
        warns = []
        validate_story(story, warnings=warns)
        self.assertEqual(len(warns), 2)
        self.assertIn('"n1"', warns[0])  # out 无 in 在前
        self.assertIn('"n2"', warns[1])  # in 无 out 在后

    def test_transition_warning_embedded_in_lua_and_nonfatal(self):
        # 警告不中断编译，以注释形式插在 Lua 头部（编辑器 Lua 预览可见）
        story = make_story(
            [
                {"id": "n1", "type": "transition", "phase": "in", "dir": "lr"},
                {"id": "nend", "type": "end"},
            ]
        )
        lua = compile_story(story)
        self.assertTrue(lua.startswith("-- lomc 警告："))
        self.assertIn("node_n1", lua)

    def test_dice_band_text_pipe_sanitize(self):
        # 结果带文本里的 ASCII | 换成全角｜（游戏用 | 分隔文本与条件）
        import lomc.dice_data as dd

        saved = dd._META
        try:
            dd._META = {
                "Test_Check": {
                    "max": 60,
                    "bands": [
                        {"text": "你|我", "cond": "<60"},
                        {"text": "好|坏", "cond": ">=60"},
                    ],
                }
            }
            lua = compile_story(
                linear_story(
                    {
                        "id": "n1",
                        "type": "dice",
                        "check": "Test_Check",
                        "options": [
                            {
                                "goto_大成功": "",
                                "goto_成功": "nend",
                                "goto_失败": "nend",
                            }
                        ],
                    }
                )
            )
            self.assertIn('dice_opts1[1] = "你｜我|<60"', lua)
            self.assertIn('dice_opts1[2] = "好｜坏|>=60"', lua)
        finally:
            dd._META = saved

    def test_dice_two_band_big_success_ignored_warning(self):
        # 2 带检查点无独立大成功档：goto_大成功 被忽略（最优带按 goto_成功 分支）
        story = make_story(
            [
                {
                    "id": "n1",
                    "type": "dice",
                    "check": "S0205_01_001",
                    "options": [
                        {"goto_大成功": "na", "goto_成功": "nb", "goto_失败": "nb"}
                    ],
                },
                {"id": "na", "type": "focus", "character": "player"},
                {"id": "nb", "type": "focus", "character": "brother4"},
                {"id": "nend", "type": "end"},
            ]
        )
        warns = []
        validate_story(story, warnings=warns)
        self.assertTrue(any("goto_大成功 会被忽略" in w for w in warns), warns)


if __name__ == "__main__":
    unittest.main()
